feat(ci): use latest crs containers for testing
coreruleset/coreruleset pull request #2188
Opened 2021-09-05 12:01 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Turns out we were using the old version. We fell in our own trap.

2021-09-06 18:03 UTC, dune73 commented
Why is this needed? What is happening without this?

2021-09-06 18:20 UTC, fzipi commented
From the CRS perspective? Not much. But there are plenty of variables that help users with better UX. For example: I was trying to have the debug log to verify a problem in a different PR, and setting the variable in the docker-compose wasn't working. After updating, now I can just define `MODSEC_DEBUG_LOG` as env var, without changing anything else.

2021-09-06 18:28 UTC, dune73 commented
Thanks.

But it also means we should update this when we do a new release, don't we? Or should we better wait a few weeks, since docker containers would get the new rule set automatically otherwise?

2021-09-06 18:54 UTC, fzipi commented
Containers always get the latest `stable` version. For testing we use (and recommend) that you clone/unzip your own version, and mount the resource externally.

For example, the Github action test mounts the branch tested instead of using what's in the container.

2021-09-20 10:36 UTC, franbuehler approved these changes
Looks almost good to me. owasp/modsecurity-crs:apache points to latest image version.
[owasp/modsecurity-crs:nginx](https://hub.docker.com/layers/owasp/modsecurity-crs/nginx/images/sha256-c535e1bff76c556c8f99095fd000df8233f41f8ba9540418b6fe71f9f33c72f9?context=explore) does not. 
Also see [this issue here](https://github.com/coreruleset/modsecurity-crs-docker/issues/44).

2021-09-20 10:43 UTC, franbuehler requested changes
Looks almost good to me. owasp/modsecurity-crs:apache points to latest image version.
[owasp/modsecurity-crs:nginx](https://hub.docker.com/layers/owasp/modsecurity-crs/nginx/images/sha256-c535e1bff76c556c8f99095fd000df8233f41f8ba9540418b6fe71f9f33c72f9?context=explore) does not. 
Also see [this issue here](https://github.com/coreruleset/modsecurity-crs-docker/issues/44).

2021-09-24 13:18 UTC, fzipi commented
Fixed issue with latest containers.

2021-09-30 15:18 UTC, fzipi commented
@franbuehler Can you review again?

2021-10-03 21:30 UTC, fzipi commented
@franbuehler Can you review again?

2021-10-04 13:02 UTC, franbuehler approved these changes

2021-10-04 15:50 UTC, merged