fix_2118
coreruleset/coreruleset pull request #2189
Opened 2021-09-06 03:24 UTC by NiceYouKnow

Remove the fuzzy regularity of the 942310 rule。

2021-09-06 03:39 UTC, NiceYouKnow commented
@franbuehler , #2118 already resolved, please review.

2021-09-07 08:29 UTC, theseion requested changes
Thanks! Just needs a bit more documentation.

2021-09-07 08:29 UTC, theseion commented on tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942310.yaml
> +          #This is a payload with the fuzzy regularity removed. Now, it is a white sample. regex: [\"'`]\s+and\s*?=\W
Move this to the description:
```yaml
desc: |
    Chained SQL injection attempts 2/2.

    This test originally checked the expression `[\"'`]\s+and\s*?=\W`. We opted to remove that expression as it 
    does not appear to match anything useful (https://github.com/coreruleset/coreruleset/issues/2118).
    This test now checks that no match occurs for something that would have matched the original expression.
```

2021-09-07 08:29 UTC, theseion commented on tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942310.yaml
> +    desc: "chained SQL injection attempts 2/2"
Please describe the regular expression this test is designed to check.

2021-09-07 08:29 UTC, theseion commented on tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942310.yaml
> +    desc: "chained SQL injection attempts 2/2"
Please describe the regular expression this test is designed to check.

2021-09-07 08:55 UTC, theseion commented
@NiceYouKnow You can use the `desc` property for describing the test, no need for comments (`#`). Use `data: |` for multiline descriptions, as I've done in the example.

2021-09-09 08:58 UTC, dune73 commented
Thanks @theseion.

@NiceYouKnow, we have talked about your welcome PR in our dev meeting earlier this week and we assigned the review to @theseion, since @franbuehler is a bit overburdened with many other issues / PRs / reviews. I hope you can follow the suggestion of @theseion.

-> (Results of the August project meeting](https://github.com/coreruleset/coreruleset/issues/2185#issuecomment-913804183)

2021-09-09 09:20 UTC, dune73 commented
Thank you @NiceYouKnow.

2021-09-09 19:18 UTC, theseion requested changes
Looks good to me. Please update the descriptions as proposed and we are good to go.

2021-09-09 19:18 UTC, theseion commented on tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942310.yaml
> +      This is a regular test, this is a valid payload: \(\s*?select\s*?\w+\s*?\(
Pleas change this to:

```suggestion
This test checks for a positive match of `\(\s*?select\s*?\w+\s*?\(`.
```

2021-09-09 19:18 UTC, theseion commented on tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942310.yaml
> +      This is a regular test, this is a valid payload: order\s+by\s+if\w*?\s*?\(
Please change this to:
```suggestion
      This test checks for a positive match of `order\s+by\s+if\w*?\s*?\(`.
```

2021-09-10 07:25 UTC, theseion approved these changes

2021-09-10 07:27 UTC, theseion commented
Thanks again!

2021-09-10 07:42 UTC, merged