Add new rules 920520 and 920521 to check for valid accept-encoding
coreruleset/coreruleset pull request #2357
Opened 2022-01-20 16:15 UTC by franbuehler

This PR adds two new rules that checks for valid Accept-Encoding request headers.

- Rule 920520 at PL1 only checks for length not greater than 50 characters.
- Rule 920521 at PL3 checks for valid known Accept-Encoding headers.

The PR also adds tests.

We first wanted to check for length in PL3 rule as well, but I think this does not make sense because we already check in rule 920520 at PL1.

Only rule at PL1 920520 blocks CVE-2022-21907. Rule 920521 does not, because `*` is allowed inside the header.

Sources: 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
https://www.iana.org/assignments/http-parameters/http-parameters.xml#http-parameters-1
https://github.com/antx-code/CVE-2022-21907

Feedback welcome.

2022-01-20 16:38 UTC, theMiddleBlue commented
Looks great! Agree with not checking the length for the stricter rule. I would like to stress a bit the regex of 920520 maybe creating a new backend on the sandbox for this PR

2022-01-20 16:58 UTC, fzipi commented on rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
> +    t:none,t:lowercase,t:length\
@franbuehler Looks like a comma is missing here at the end :)

2022-01-20 17:00 UTC, franbuehler commented on rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
> +    t:none,t:lowercase,t:length\
Oh thank you for helping to find the lint error.
I'll fix that.

2022-01-21 20:22 UTC, franbuehler commented
Thank you for testing, @theMiddleBlue!!
It looks good.
Oh, yes, the msg of the PL1 rule is a bit ugly, you're right. I'll change it.

2022-02-05 12:29 UTC, fzipi approved these changes
This is a good one, and looks solid.

Thanks @franbuehler for the PR!

2022-02-05 12:31 UTC, fzipi commented
Oh, wait. @franbuehler Are you going to change the message before merging?

2022-02-05 17:03 UTC, theseion commented
How about `Accept-Encoding header exceeded sensible length`? `sensible` could also be replace by `configured`, for example.

2022-02-07 11:22 UTC, fzipi requested changes
We still need to change the text to re-approve this one.

2022-02-11 11:32 UTC, fzipi approved these changes
LGTM now!

2022-02-11 11:33 UTC, merged

2022-02-12 10:36 UTC, 877509395 reviewed
"@gt 50" where 50 come from?

2022-02-12 11:01 UTC, fzipi commented
It is an heuristic based on the names from the RFC and [iana assignments](https://www.iana.org/assignments/http-parameters/http-parameters.xml#content-coding).