docs: update policy to include signed releases
coreruleset/coreruleset pull request #2465
Opened 2022-03-31 11:33 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

- Update security policy to include release verification
- Add pointer to the sandbox to verify bypasses

2022-03-31 15:34 UTC, theseion requested changes

2022-03-31 15:34 UTC, theseion commented on SECURITY.md
> +Our email is [security@coreruleset.org](mailto:security@coreruleset.org). You can send us encrypted email using the same GPG key we use to sign releases fingerprint: `3600 6F0E 0BA1 6783 2158 8211 38
```suggestion
Our email is [security@coreruleset.org](mailto:security@coreruleset.org). You can send us encrypted email using the same GPG key we use to sign releases, fingerprint: `3600 6F0E 0BA1 6783 2158 8211 38EE ACA1 AB8A 6E72`.
```

2022-03-31 22:07 UTC, dune73 commented
This is written in a very clear way and I do not have any comments. (Yet I did not try out the commands).

Thank you very much. LGTM.

2022-04-01 09:56 UTC, theseion approved these changes

2022-04-01 11:16 UTC, merged