Fix FP in MySQL data leakage
coreruleset/coreruleset pull request #2490
Opened 2022-04-11 07:57 UTC by azurit

FP is doing this pattern:
`Warning.*mysql_.*`

I'm not sure what error message is this supposed to match but while trying to google it, i found only PHP error messages (see below), so i assume it's for PHP errors.

To lower FPs, i made pattern more tighter:
`Warning.{1,10}mysql_[a-z_()]{0,26}`

For the first part of the pattern (`Warning.{1,10}`), i saw multiple versions of the error message:
```
Warninig: mysql_...
Warninig:mysql_...
Warninig : mysql_...
Warninig:   mysql_...
```

For the second part (`mysql_[a-z_()]{0,26}`), i assume we are try to catch a function name (list: https://www.php.net/manual/en/ref.mysql.php ) and longest function name (`mysql_real_escape_string`) has 24 characters (+2 for brackets). Limiting length of matched data will also create nicer error messages.

Various error messages matching problematic pattern:
```
Warning: mysql_close(): 5 is not a valid MySQL-Link resource

Warning: mysql_fetch_array(): supplied argument is not a valid MySQL result

Warning: mysql_query() [function.mysql-query]: Access denied for user 'root'@'localhost' (using password: NO) in /home/adamjudk/public_html/airlinesimulator/login.php on line 18

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource

MYSQL PHP Warning: mysql_query() expects parameter 1 to be string

Warning: mysql_query() [function.mysql-query]: A link to the server could not be established in /home/adamjudk/public_html/airlinesimulator/login.php on line 18

Warning: mysql_ functions are deprecated as of PHP 5.5.0, and will be removed in the future. Instead, the MySQLi or PDO_MySQL extension should be used.

```

2022-04-11 14:50 UTC, theseion requested changes
This is a great change, I think. I'd love it if you could add a data file for the regular expression. Then you could also easily add the comment I suggested in the inline review comment.

2022-04-13 04:13 UTC, azurit commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
The first part of the regexp should be affected too, isn't it? So:
`(?:Warning.{1,10})mysql_(?:[a-z_()]{1,26})`

2022-04-13 04:47 UTC, theseion commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
No, the issue is not grouping but ranges that start at 0. So `{1,10}` is ok, but `{0,10}` will trip up the parser. The group I added is necessary to make the entire expression optional. I basically replaced the `0` with a `?`.

2022-04-13 05:00 UTC, azurit commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
Hm, i don't like this solution. I thought you just added (?:) and didn't noticed that you changed 0 to 1.

2022-04-13 05:04 UTC, azurit commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
Also, group `(?:)` does not make it optional.

2022-04-13 05:21 UTC, azurit commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
Do we need to bypass this only because of Coraza?

2022-04-13 15:29 UTC, theseion commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
Yes, but only because there's no other engine we know of that uses re2. In general it would be for every engine supporting re2.

2022-04-17 06:01 UTC, azurit commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
Can you check it now? Thanks.

2022-04-17 06:12 UTC, azurit commented
Any hints how can i get rid of all the commits after i did a rebase?

2022-04-18 08:27 UTC, theseion commented
There shouldn't be any, TBH... I'll take a look.

2022-04-18 08:58 UTC, theseion commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> +    SecRule RESPONSE_BODY "@rx (?i)(?:supplied argument is not a valid MySQL|Column count doesn't match value count at row|mysql_fetch_array\(\)|on MySQL result index|You have an error in your SQL sy
Looks good.

2022-04-18 08:59 UTC, theseion approved these changes
I've adjusted the regexp-assemble comment since updating chained rules isn't currently supported (and there was a copy paste error with).

I've also made a small adjustment to the regex (lowercase `[a-z]`).

The rest looks good. Thanks!

2022-04-18 16:08 UTC, lifeforms commented
Looks good to me!

2022-04-18 16:08 UTC, merged