Additional protocols for RFI rule 931130
coreruleset/coreruleset pull request #2572
Opened 2022-05-17 15:20 UTC by karelorigin

This PR contains fixes for bypasses that were originally found and submitted by @hussein98d in `9LB1ZNRE`, `V4DR54LM` and `J27G5EJX`.

2022-05-17 15:39 UTC, lifeforms commented
> I noticed that many SSRF/RFI rules are only evaluated against query parameters. Perhaps including XML, headers, and other common injection points is also a good idea?

I agree.

Our generic RFI rule (931130) can't run on request headers, it will fire on most http:// links and this will give false positives on the Referer and the User-Agent request headers.

However, for specific SSRF rules, the patterns are pretty much a sure indicative of an attack, and false positives don't seem so much of a problem, so I agree we should check all the variables.

I think the best way is to make a new rule with the other protocols (except http/https) and have that rule cover all variables including headers and XML.

2022-05-18 10:33 UTC, karelorigin commented
I've just pushed another fix for a bypass submitted by @hussein98d in `YJGXRICC`

2022-05-20 12:17 UTC, dune73 commented
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

2022-05-21 19:30 UTC, lifeforms commented
`ldaps` is also a protocol (secure LDAP), `ldapi` is also there. Could we try to come up with an exhaustive list of protocols? I think there were also a bunch of "PHP wrappers" posted in a submission, which are basically similar to protocols.

2022-06-14 12:58 UTC, fzipi commented
Now that we merged the 934120 update, you can use the same technique used there in lines https://github.com/coreruleset/coreruleset/blob/51b5d465d9b7db3ec7654762165eafaa6c9b79ae/util/regexp-assemble/data/934120.data#L14-L19  to include the url-schemes list.

2022-06-24 07:57 UTC, dune73 commented
Assigning @fzipi based on our separate spreadsheet.

2022-06-24 13:26 UTC, fzipi commented
@karelorigin Just a question: are you going to have time to update this one, or do you want me to add the latest changes? I know you are very busy these days...

2022-07-09 16:58 UTC, karelorigin commented
Sorry for the wait! I should be able to get the necessary work done before the weekend is over. Is the include directive global? Can I reference it in other data files? @fzipi

2022-07-18 21:10 UTC, karelorigin commented
Awesome @fzipi, I'll get on that as soon as I can.

2022-09-18 11:38 UTC, fzipi commented
@karelorigin Hey! Any news on this one? Do you need help?

2022-09-19 12:41 UTC, fzipi commented
Solved conflicts.

2022-09-19 12:59 UTC, fzipi commented
Fixed also:

- moved to including url-schemes
- fixed `file://` inclusion as url-scheme 🤦
- fixed dependent rule 934120.

2022-09-19 18:32 UTC, theseion requested changes

2022-09-19 18:32 UTC, theseion commented on rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
>  #   util/regexp-assemble/regexp-assemble.py update
```suggestion
#   util/regexp-assemble/regexp-assemble.py update 934120
```

2022-09-19 18:32 UTC, theseion commented on rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
>  # org.apache.commons.io.IOUtils to access internal files, so this has been added
```suggestion
# org.apache.commons.io.IOUtils to access internal files, so this has been added
#
#   # Regular expression generated from util/regexp-assemble/data/931130.data.
# To update the regular expression run the following shell script
# (consult util/regexp-assemble/README.md for details):
#   util/regexp-assemble/regexp-assemble.py update 931130
#
```

2022-09-19 18:40 UTC, theseion approved these changes
LGTM!

2022-09-19 18:41 UTC, merged

2022-09-19 18:41 UTC, fzipi commented
Thanks @karelorigin for pushing this change!