feat(rce): additional signatures for NodeJS RCE (934100)
coreruleset/coreruleset pull request #2573
Opened 2022-05-17 16:13 UTC by karelorigin

This PR contains fixes for bypasses that were originally found and submitted by @hussein98d in `5ZLKNU33`.

2022-05-20 12:17 UTC, dune73 commented
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

2022-05-23 20:24 UTC, karelorigin commented
Hi @lifeforms, I'd love some feedback on your feedback (ha!). I was never forwarded any `process.config` or `process.mainModule` bypasses by @hussein98d. Also, I noticed some room for improvement in this rule (in general, not just applicable to this patch).  For example, the `jsDecode` transformation is not used, even though JavaScript escape sequences can be used in NodeJS, which should make it possible to completely bypass this rule using something like:

```
x=\u0072equire("url");y=x.parse("http://x.com");c\u006fnsole.log(y)
```

I could definitely fix this but I might need a couple of days since my hands are full at the moment. Adding the `jsDecode` transformation will also allow me to simplify the regexes I've added as a bonus.

2022-06-27 17:26 UTC, karelorigin commented
@dune73, I've noticed that the tests indeed fail. @fzipi have been looking into it but are so far unable to track down the root cause. I'll definitely get back on that.

I noticed that whitespaces are also an issue with this rule. The following payload will bypass the rule in its current state:

```javascript
this. constructor
```

Do you think it would be okay for me to add the removeWhitespace transformation + rework the regular expressions to account for that change?

Would be great if you could update the assessment after that's all finished :)

2022-06-27 20:43 UTC, dune73 commented
We'll certainly update the assessment. No worries there.

And thank you for investigating the test failure. If you can't seem to find the root cause, we can try and call the cavalry.

As for the whitespace: Please confirm that `this. constructor` is actually a potential exploit, so we really ought to catch it.

The rule itself has quite a few tests, so I think it's quite safe to play around with additional transformations. Feel free to add the `t:removeWhitespace`.

2022-06-28 09:51 UTC, lifeforms commented
I think `this['constructor']` will also work, or not? Should the regexp be updated to catch this as well?

2022-06-28 10:53 UTC, karelorigin commented
@dune73, thank you. @fzipi told me that he managed to track down the test issue to the transformations. After the other issue is resolved, I'll be sure to add the `removeWhitespace` transformation.

2022-06-30 07:51 UTC, dune73 commented
@fzipi are you able to provide guidance how to get the tests up and running again before you leave keyboard for a week?

I'd hate to ask you to write regular expressions on your mobile phone during a holiday...

2022-06-30 07:53 UTC, dune73 commented
@theseion: @karelorigin sees a need to have regex-assembly provide evasion protection for one or two source regexes in this PR. Can you advice?

2022-06-30 14:17 UTC, fzipi commented
> @fzipi are you able to provide guidance how to get the tests up and running again before you leave keyboard for a week?
> 
> I'd hate to ask you to write regular expressions on your mobile phone during a holiday...

Sure, let me take a look.

2022-06-30 18:24 UTC, fzipi commented
@dune73 We discussed this in the channel and also with @karelorigin . The base64decode is breaking the jsDecode there. We need to have a different order for transformations, with jsdecode being first, or ask @lifeforms if we want to keep the base64 decode there.

2022-06-30 18:32 UTC, karelorigin commented
This is true. The base64Decode transformation appears to cause the issue. Applying it last would technically solve the problem, but isn't ideal since it wouldn't be able to detect cases where the base64 encoded input also has JavaScript escape sequences.

2022-06-30 19:01 UTC, theseion commented
@dune73 @karelorigin regexp-assemble currently has two modes of evasion prevention, one for Windows and one for Unix shells. I'm not sure whether that is exactly what you want (documented here: https://coreruleset.org/docs/development/regexp_assemble/#command-line-evasion-preprocessor). Here's an example: https://github.com/coreruleset/coreruleset/blob/64e5844cb2dde349eba9529504055bc646c3377f/util/regexp-assemble/data/932100.data#L94.

There's an alternative that would also work with the current facilities: using the [`template` processor](https://coreruleset.org/docs/development/regexp_assemble/#template-preprocessor). The regex from above can be simplified to
```
process(?:(?:\.|[\['"`])env)\b
```
That gives you a fixed string that you can template like this:
```
##!> template stop-evasion (?:\.|[\['"`])
process(?:{{stop-evasion}}env)\b
##!<
```

I'm open to other ideas.

2022-06-30 21:20 UTC, dune73 commented
Thank you @fzipi. We can take it from here.

2022-07-09 17:00 UTC, karelorigin commented
Appreciate the suggestion @theseion, I'll take a look. What about the `base64Decode` transformation @dune73? Are we cool with the potential (but still rare) bypasses that might occur if we apply that one last?

2022-07-17 16:00 UTC, lifeforms commented
I don't think the base64Decode is a must, and I have no problems if you remove it.

I remember adding it defensively, because I've seen a lot of PHP code injections where base64 is used to encode PHP source - perhaps to bypass, but also as it's a useful string format that doesn't require escaping etc. That's why when I thought of Javascript injections, the attackers might do the same and it might be a smart failsafe to do this decode. But I have not seen it in the wild, we don't have this on many other rules either, and I think it's acceptable to remove it.

2022-07-31 14:20 UTC, theseion requested changes
Very nice use of regexp-assembl! ;)

2022-07-31 14:20 UTC, theseion commented on util/regexp-assemble/data/934100.data
> +##!> assemble
Please indent nested processors to improve readability (will not repeat for the same issues below)

2022-07-31 14:20 UTC, theseion commented on util/regexp-assemble/data/934100.data
> +
```suggestion
##! Add function names here. Currently empty.
```

2022-07-31 14:20 UTC, theseion commented on util/regexp-assemble/data/934100.data
> +##!    ##!> assemble
No need to use nested processors for concatenating for borth `func` and `js-call` (will not repeat for same issues below).

2022-07-31 14:20 UTC, theseion commented on util/regexp-assemble/data/934100.data
> +    ##!> assemble
Why do we need to add the function names here too?

2022-07-31 14:20 UTC, theseion commented on util/regexp-assemble/data/934100.data
> +
```suggestion
##! Add property names here. Currently empty.
```

2022-08-15 19:09 UTC, theseion commented
@karelorigin any updates on this issue?

2022-11-11 11:25 UTC, fzipi commented
@theseion We should be able to fix this one now with the new features in regexp-assembly, right?

2022-11-11 17:36 UTC, theseion commented
Yes, but it needs the toolchain. Regexp::Assemble will generate an invalid regex.

2022-11-20 13:36 UTC, theseion commented
I'm picking this one up again. We have switched to crs-toolchain, so I should be able to finish it.

2022-11-20 16:21 UTC, theseion commented
I've finalized the PR. Notes:

    - rebase onto v4.0/dev
    - add missing dynamic property access
    - add missing `argv` porperty
    - assume that every method name of `process` has a twin with `sync`
      suffix
    - add missing `require` toplevel object
    - use definitions for simple expressions, instead of assemble blocks

@karelorigin please make sure that I didn't mess up anything.

2022-11-25 19:13 UTC, karelorigin reviewed
@theseion there are still some changes that I don't entirely understand. Could you explain to me why the paranoia level was upped to 2? Also, JavaScript is case-sensitive, why are we checking for lowercase values?

2022-11-25 19:38 UTC, theseion commented
>Also, JavaScript is case-sensitive, why are we checking for lowercase values?

I've added the `i` flag (`##!+ i`) to ignore case while matching.

>Could you explain to me why the paranoia level was upped to 2?

Good catch! TBH, I didn't change that, AFAICR. @dune73 the rule should remain at PL1, correct?

2022-11-25 19:53 UTC, dune73 commented
Very good catch. Given the rule was not moved to the PL2 range in the file, this is clearly a mistake. I suggest to retag as PL1.

2022-11-25 20:12 UTC, theseion commented
Done

2022-11-25 20:27 UTC, karelorigin commented
> I've added the `i` flag `(##!+ i)` to ignore case while matching.

Yes, so case-insensitivity for a case-sensitive language? 😅 

I also noticed that all the whitespaces are removed to make use of the earlier added `removeWhitespace` transformation. Are we sure we want to go this route for all entries? In my opinion, it confuses things when whitespaces are not explicitly defined in the middle of a pattern. `newfunction` being one of those. We should be fine adding them where it makes sense because of the multi match.

Do all methods on [L88](https://github.com/coreruleset/coreruleset/pull/2573/files#diff-2ed755124ce6baa89780fe8d7edab80f7d2672f57d51072c2ce1ec9d166c0fb2R88) share the optional sync prefix? If not, it might make sense to split these into two (or nested) assemble blocks. That way, we are a bit closer to our 'no false positives at PL1' objective.

2022-11-26 09:03 UTC, theseion commented
> Yes, so case-insensitivity for a case-sensitive language? 😅

Sorry, i misread that :) I didn't really think about JS being case-sensitive, but you're right of course. I'll revert.

>In my opinion, it confuses things when whitespaces are not explicitly defined in the middle of a pattern. newfunction being one of those. We should be fine adding them where it makes sense because of the multi match.

Excellent point. The reason I removed all of them was that I realized that we would have to add tons of `\s*` everywhere to properly match (especially before and after brackets and parentheses), but then discovered that the rule already removed white space. I had not realized, however, that `multiMatch` was enabled. I will revert that change as well.

>Do all methods on [L88](https://github.com/coreruleset/coreruleset/pull/2573/files#diff-2ed755124ce6baa89780fe8d7edab80f7d2672f57d51072c2ce1ec9d166c0fb2R88) share the optional sync prefix? If not, it might make sense to split these into two (or nested) assemble blocks. That way, we are a bit closer to our 'no false positives at PL1' objective.

No, probably not. I just go very annoyed with the list and figured it wouldn't matter if we matched a couple more. The obvious additions that might cause issues are (excluding things like `chmod` that are obviously things we would want to block):
- close
- exec
- exists
- link
- open
- read
- rename
- spawn
- unlink
- write

All of these existed in the list before only with the `sync` suffix. What we match:
- `.close(`
- `.close.call(`
- `["close"]`

Personally, I think we're safe and I think the simplified maintenance of that function list is worth it. @dune73, what's your opinion?

Thanks for taking such a thorough look @karelorigin!

2022-12-05 16:23 UTC, dune73 commented
Fine from my side. Feel free to merge.

2022-12-05 19:10 UTC, theseion approved these changes

2022-12-05 19:11 UTC, merged