feat(list): update php errors list
coreruleset/coreruleset pull request #2663
Opened 2022-06-26 15:26 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

This PR will update the PHP errors list. I've added the description to the procedure I'm following to get, with some caveats, all the errors that might be disclosing information.

Still need to remove lines,will mark when ready to review.

2022-06-29 06:11 UTC, theseion requested changes
Great work! I've tweaked the English a bit.

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +# Small post processing might be done to adjust strings that might cause false positives. Examples are lines too short,
```suggestion
# Post processing might be necessary to adjust strings that can cause false positives, such as
# - line is very short
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +# or very common Enlgish sencentes (e.g. `Can use`, `Attribute`, etc.). There also text coming from php unit/regression
```suggestion
# - line is a (partial) common English sentence, like `Can use`, `Attribute`, etc.
# - text coming from php unit/regression tests, like 'DROP TABLE IF EXISTS test_bug_71863`
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +# tests, like 'DROP TABLE IF EXISTS test_bug_71863` that we need to clean.
```suggestion
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +# The easiest way is to split in lines when a format string is found. This will shorten the texts, but
```suggestion
# The easiest way is to split a line whenever a format string is found. This will shorten the texts but,
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +# then we can sort who are the ones more fit for being in this file.
```suggestion
# then we can sort out the ones we don't want to include more easily.
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +# - text with just one word (too easy for FP), or one word, one space (optional) and one non-word (optional).
```suggestion
# - text with just one word (likely to be FP), or one word, one space (optional) and one non-word (optional),
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +#   this will match things like `Collect "`, `Method` or `Class `.
```suggestion
#   which will match things like `Collect "`, `Method` or `Class `.
```

2022-06-29 06:11 UTC, theseion commented on rules/php-errors.data
> +#   - `ggrep -E -h -r --exclude="*.phpt" '_error([0-9])?\(' * | awk -F\" '/%/ { print $2;} ' | sed -e 's/ \\$/ "/g' -e 's/%[zlp][ud]/\n/g' -e 's/%[a-z]/\n/g'  -e 's/%\.\*s/\n/g' | sort | uniq | ggrep
```suggestion
#   - `grep -E -h -r --exclude="*.phpt" '_error([0-9])?\(' * | awk -F\" '/%/ { print $2;} ' | sed -e 's/ \\$/ "/g' -e 's/%[zlp][ud]/\n/g' -e 's/%[a-z]/\n/g'  -e 's/%\.\*s/\n/g' | sort | uniq | grep -E -v '^\w+\s?\W?$' | grep -E -v '^\W+$'
```

2022-06-29 18:14 UTC, fzipi commented on rules/php-errors.data
> +# `ggrep -h -E -r -o --exclude="*.phpt" '\w+_error([0-9])?\(' * | sort | uniq`
Oops, this should be `grep` 🤣

2022-06-30 04:51 UTC, theseion commented on rules/php-errors.data
> +# `ggrep -h -E -r -o --exclude="*.phpt" '\w+_error([0-9])?\(' * | sort | uniq`
Oops :) removed the wrong character 😛.

2022-06-30 12:08 UTC, fzipi commented on rules/php-errors.data
> +# `ggrep -h -E -r -o --exclude="*.phpt" '\w+_error([0-9])?\(' * | sort | uniq`
Fixed.

2022-06-30 19:04 UTC, theseion approved these changes
LGTM

2022-07-16 14:18 UTC, fzipi commented
This error is weird in the tests:
```
regression (modsec2-apache)
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 79 MB
```
I will fire up again.

2022-07-17 16:04 UTC, theseion commented
The run keeps stalling at
```
plugins: github-actions-annotate-failures-0.1.7, ftw-1.3.0
collecting ... collected 3014 items
```

2022-07-18 18:26 UTC, fzipi commented
Well, rebased to see if something changes...

2022-07-19 21:38 UTC, fzipi commented
Clearly there is a problem with this file and ftw. Go-ftw seems to work good. Will debug later/tomorrow.

2022-07-20 09:41 UTC, fzipi commented
We might need to trim down the list a bit. It is matching valid HTML 🤔

2022-07-24 15:49 UTC, theseion commented
Ah yes. That's an issue we have to fix: the `X-CRS-Test` header rule is currently expected to be the only one triggered when writing a marker. Depending on the rules, that request could trigger one or more other rules though and then the loop would never end. Random idea: could we disable all other rules when the test header rule is triggered?

2022-07-27 13:44 UTC, fzipi commented
So... is this ready to merge @theseion?

2022-07-27 19:56 UTC, theseion commented
Did you want to maybe document why you removed those entries? Because they would come back in the next time we generate the list.

2022-08-03 18:06 UTC, fzipi commented
I think the removed lines speak for themselves.

2022-08-03 18:37 UTC, theseion approved these changes
LGTM

2022-08-03 18:58 UTC, merged