fix(932100): update data list
coreruleset/coreruleset pull request #2676
Opened 2022-06-30 21:14 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Updated data list based on unix-shell.data.

I've also added some regexes for programming languages with versions.

Fixes #2673 .

2022-07-16 13:33 UTC, fzipi commented
- Added more tests
- Changed test titles to match our generic naming

2022-07-27 14:07 UTC, RedXanadu commented
Sorry, I haven't had time to look at this one either, yet. It, also, is still on my todo list.

2022-07-29 14:34 UTC, dune73 commented
I think the following items would profit from `@`.

```
ash
bridge
bundler ...
column
dd
docker
finger
genie
gimp
install
latex
```

2022-07-31 14:00 UTC, theseion requested changes
\+ things spotted by @dune73

2022-08-01 17:45 UTC, fzipi commented
Addressed comments, and added more bare English words with `@`. Also, removed some repeated ones.

2022-08-01 18:53 UTC, theseion approved these changes

2022-08-01 20:12 UTC, RedXanadu commented
Oops, sorry: I didn't follow up my earlier comment. After looking at this more closely, the same as with #2677: I don't think there are concerns about adding in anti-evasion patterns as there isn't a specific suffix being searched for, so it's fine (e.g. `lua5"".4` won't work as an evasion as it will still match on `lua`.)

2022-08-02 10:29 UTC, fzipi commented
In summary: adding the numbers won't give us added value in this case, so I'm reverting them back to their original positions in the file and removing the specific cases.

2022-08-03 16:35 UTC, theseion commented on util/regexp-assemble/data/932100.data
> +GET@
Wasn't `GET` removed earlier??

2022-08-03 16:36 UTC, theseion commented on util/regexp-assemble/data/932100.data
> +GET@
Ah, it was moved from the top.

2022-08-03 16:36 UTC, theseion approved these changes
LGTM

2022-08-03 16:54 UTC, lifeforms commented
Tests are failing now, but that could be due to a temporary problem with our pipeline that should be solved now. Re-running jobs.

2022-08-03 17:01 UTC, lifeforms commented
Two test failures persist:

running 932100-28: 💥 failed in 4.404215ms - POST data: `arg=;gcc10.1`
running 932100-29: 💥 failed in 4.240415ms - POST data: `arg=;irb31`

2022-08-03 17:42 UTC, fzipi commented
That happens after the last update from @RedXanadu. I've removed the suffix search. But looks like now we are not matching anymore.

2022-08-03 18:34 UTC, theseion commented
Note that this issue is affected by the same thing as #2677. We need to figure out how we ignore `python` but still catch `python3`. I've suggested adding an additional symbol for an adjusted anti-evasion pattern in the other PR.

2022-09-17 12:15 UTC, fzipi commented
Updated:
- `irb` -> `irb~`
- `gcc` -> `gcc~`

2022-09-17 12:19 UTC, fzipi commented
🤔 Looks like they fail when using `~`... but didn't failed previously. Let's try removing that.

2022-09-19 05:05 UTC, theseion commented
I might be stating the obvious but you'll need to change `gcc` to `gcc~` in the data file for the new test to work (same for `irb`).

2022-09-19 12:29 UTC, fzipi commented
Thanks for the tips. Looks like working now. Following approval, let's merge then.

2022-09-19 12:30 UTC, merged