fix(951240): update rule based on regex
coreruleset/coreruleset pull request #2831
Opened 2022-10-03 01:20 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

This is the last fix that will enable the regexp updated lint check (#2744).

2022-10-03 05:28 UTC, theseion reviewed
Looks good to me, but what's with the regressions?

2022-10-03 12:52 UTC, fzipi commented
Huh. This is weird. I cannot see a data file for this rule 🤔

2022-10-03 18:45 UTC, theseion commented
There isn't... We added one for 951230 but the rule was changed in 286092cca873a8521b21ad4431704cb1d63cd8a3, so it's no longer chained (need to rename the data file).

Could you also update the comment on 951230 to match the other regexp-assemble comments?

How did you make the change to 951240 if there's no data file...? 😅 Anyway, we should take the opportunity and create the data file.

2022-10-04 00:35 UTC, fzipi commented
Decomposed regexp, and looks right. But the generated changes the rule. Probably because the initial `(?i` in the original rule, instead of using `(?i)(`?

2022-10-04 05:03 UTC, theseion requested changes

2022-10-04 05:03 UTC, theseion commented on util/regexp-assemble/data/951240.data
> +PG::[a-zA-Z]*Error
```suggestion
PG::[a-z]*Error
```

2022-10-04 05:03 UTC, theseion commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> -SecRule RESPONSE_BODY "@rx (?i:PostgreSQL query failed:|pg_query\(\) \[:|pg_exec\(\) \[:|PostgreSQL.{1,20}ERROR|Warning.*\bpg_.*|valid PostgreSQL result|Npgsql\.|PG::[a-zA-Z]*Error|Supplied argument
Add regexp-assemble comment before rule.

2022-10-04 05:03 UTC, theseion commented on rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> -SecRule RESPONSE_BODY "@rx (?i:PostgreSQL query failed:|pg_query\(\) \[:|pg_exec\(\) \[:|PostgreSQL.{1,20}ERROR|Warning.*\bpg_.*|valid PostgreSQL result|Npgsql\.|PG::[a-zA-Z]*Error|Supplied argument
Fix regexp-assemble comment on 951230.

2022-10-04 05:04 UTC, theseion commented
> Decomposed regexp, and looks right. But the generated changes the rule. Probably because the initial `(?i` in the original rule, instead of using `(?i)(`?

Yes, flags in regexp-assemble are always prefixed as `(?<flag>)`, but `(?<flag>:<regex>)` is a valid form.

2022-10-04 19:37 UTC, theseion commented
I wanted the comments to be the same as the others, so I fixed my own review comments too.

2022-10-04 19:38 UTC, theseion approved these changes

2022-10-04 20:10 UTC, merged