feat(cmdline): extend it to support new evasions
coreruleset/coreruleset pull request #2907
Opened 2022-10-30 22:59 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

To be commented extensively.

2022-11-01 22:35 UTC, theseion requested changes
Great stuff!

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +##! - at least one char
```suggestion
##! - at least one character
```

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +##! -
```suggestion

```

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +##! starting tokens prefix
```suggestion
```

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +##! This is the evasion detection coming from cmdline: [\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(?:\x5c)?
```suggestion
##! This is the evasion detection from the cmdline processor: [\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(?:\x5c)?
```

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +[\x5c'\"\[\]]+
Add comment: what did we change here and why (w.r.t. to the cmdline processor).

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +##!$ \b
I don't think we need this.

```suggestion
##!$ \b
```

2022-11-01 22:35 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +[a-z0-9_-]+
We need to address things like `10'000'000`. Maybe match more than x repetitions (x > 1)?

2022-11-01 22:35 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932240.yaml
> +            log_contains: id "932240"
Add test for `10'000'000`.

2022-11-01 22:35 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +#  .932230 (base rule, PL1, targets two and three chars commands)
```suggestion
#  .932230 (base rule, PL1, targets two and three character commands)
```

2022-11-01 22:35 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i)(?:[;\n\r`]|t[\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(?:\x5c)?i[\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(
The new regex is really long, even with 2 and 3 characters only. Do we need to split into two rules?

2022-11-01 22:35 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# This rule complements rule 932230 for commands of 4 characters and up, where we turn it into generic detection. Anything that uses a well-known evasion technique should be blocked at this level.
```suggestion
# This rule complements rule 932230 for commands of 4 characters and up, where we turn it into generic detection.
Anything that uses a well-known evasion technique should be blocked at this level.
```

2022-11-01 22:35 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# Regular expression generated from util/regexp-assemble/data/932220.data.
```suggestion
# Regular expression generated from util/regexp-assemble/data/932240.data.
```

2022-11-01 22:35 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i)[a-z0-9_-]+(?:\$[\x5ca-z0-9_@?!#{*-]+|[\x5c'\"\[\]]+)[a-z0-9_-]+\b" \
Didn't we want to chain this rule???

2022-11-01 22:35 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
>  # This rule is a stricter sibling of rule 932100.
Update mentions of 932100 in comments of other rules.

2022-11-02 08:35 UTC, RedXanadu commented
Why do we want to remove rules? Sorry if there is an explanation, then I cannot find it.

2022-11-02 09:58 UTC, theseion commented
Previously, the word list was split across two rules (932100 and 932105). We don't need the split anymore. We generally should not reuse rule IDs.

2022-11-02 10:15 UTC, dune73 commented
The new rule is very different from the original pair. That means existing Rule Exclusions might no longer be necessary. So better start with a new rule id.

2022-11-02 15:24 UTC, fzipi commented on util/regexp-assemble/lib/processors/cmdline.py
> +            r'''[\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(?:\x5c)?''',
Added.

2022-11-02 15:24 UTC, fzipi commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i)(?:[;\n\r`]|t[\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(?:\x5c)?i[\x5c'\"\[]*(?:\$[a-z0-9_@?!#{*-]*)?(
It's 3K now. I wouldn't split it right now.....

2022-11-02 15:25 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932240.yaml
> +            log_contains: id "932240"
Added tests for this.

2022-11-02 15:27 UTC, fzipi commented on util/regexp-assemble/data/932240.data
> +[a-z0-9_-]+
Added a test, and chained the rule so it doesn't match.

2022-11-02 17:59 UTC, fzipi commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i)[a-z0-9_-]+(?:\$[\x5ca-z0-9_@?!#{*-]+|[\x5c'\"\[\]]+)[a-z0-9_-]+\b" \
Yes, it is chained now.

2022-11-02 18:37 UTC, fzipi commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
>  # This rule is a stricter sibling of rule 932100.
Removed.

2022-11-02 20:54 UTC, theseion requested changes

2022-11-02 20:54 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +#   util/regexp-assemble/regexp-assemble.py update 9322300
```suggestion
#   util/regexp-assemble/regexp-assemble.py update 932230
```

2022-11-02 20:54 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# The chained rule will exclude german numbering.
```suggestion
# The chained rule will exclude false positives due to german thousands separators (e.g., 10'000).
```

2022-11-02 20:54 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +    SecRule MATCHED_VAR "!@rx \'[0-9]" "t:none,\
```suggestion
    SecRule MATCHED_VAR "!@rx [0-9]\s*\'\s*[0-9]" \
        "t:none,\
```

2022-11-02 20:54 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# This rule was created as a stricter sibling of previous rule 932100.
```suggestion
# This rule was created as a stricter sibling of rule 932100 (now replaced with 932230).
```

2022-11-02 21:30 UTC, fzipi commented on util/regexp-assemble/data/932240.data
> +[\x5c'\"\[\]]+
Ok, did my best, considering the hour.

2022-11-02 21:33 UTC, fzipi commented on util/regexp-assemble/data/932240.data
> +##!$ \b
I've removed this, I wonder why is not showing.

2022-11-02 21:44 UTC, theseion requested changes

2022-11-02 21:44 UTC, theseion commented on util/regexp-assemble/data/932240.data
> +##! The previous cmdline evasion detection was based on the one from modsecurity: `[\x5c'\"\[]*`
```suggestion
##! The previous cmdline evasion detection was based on the one from modsecurity: `[\x5c'\"]*`
```

2022-11-02 21:45 UTC, theseion approved these changes
❤️

2022-11-02 22:03 UTC, merged