Update 942260.data to utilise crs-toolchain formats, and rebuild 9422…
coreruleset/coreruleset pull request #2941
Opened 2022-11-02 17:36 UTC by 53cur3M3

fix 942260 update 942260.data to utilise crs-toolchain format

2022-11-02 17:38 UTC, 53cur3M3 commented
Should resolve https://github.com/coreruleset/coreruleset/issues/2860
Assembled rule required manual substition of :space: with \s\v , as :space: prevents apache starting.

2022-11-02 18:39 UTC, RedXanadu commented on util/regexp-assemble/data/942260.data
> +##!> template quotes [\"'`]
Is this template ever used?

2022-11-20 17:04 UTC, theseion requested changes

2022-11-20 17:04 UTC, theseion commented on regex-assembly/942260.ra
> +  [\"'`]\s*?
```suggestion
  {{quotes}}\s*?
```

2022-11-20 17:04 UTC, theseion commented on regex-assembly/942260.ra
>  \w\s+like\s+[\"'`]
```suggestion
\w\s+like\s+{{quotes}}
```

2022-11-20 17:04 UTC, theseion commented on regex-assembly/942260.ra
>  like\s*?[\"'`]\%
```suggestion
like\s*?{{quotes}}\%
```

2022-11-20 17:04 UTC, theseion commented on regex-assembly/942260.ra
>  [\"'`]\s*?like\W*?[\"'`\d]
```suggestion
{{quotes}}\s*?like\W*?[\"'`\d]
```

2022-11-22 20:46 UTC, theseion commented
I've taken over this PR and need someone else to do the review.

2022-11-23 16:45 UTC, fzipi approved these changes
LGTM

2022-11-23 23:02 UTC, dune73 commented
Thanks. Looks good for me too.

2022-11-24 06:37 UTC, theseion approved these changes

2022-11-24 06:38 UTC, merged