fix 942190 : Update 942190.data and rebuild rule with crs-toolchain.
coreruleset/coreruleset pull request #2946
Opened 2022-11-02 18:23 UTC by 53cur3M3

Update 942190.data and rebuild rule with crs-toolchain. Needed to replace :space: :^space: due to apache incompatibility. Needed to remove nested bracket for :space: and :nospace: inside character class"
[i2856 4967794a] Update 942190.data and rebuild rule with crs-toolchain. Needed to replace :space: :^space: due to apache incompatibility. Needed to remove nested bracket for :space: and :nospace: inside character class

2022-11-02 18:24 UTC, 53cur3M3 commented
Should resolve : https://github.com/coreruleset/coreruleset/issues/2856
On-hold until CRS-toolchain cutover

2022-11-20 17:02 UTC, theseion requested changes

2022-11-20 17:02 UTC, theseion commented on regex-assembly/942190.ra
> +{{quotes}}\s*!\s*[\"'`\w]
Use an assemble block with `{{quotes}}` as prefix so you don't have to repeat it on each of these lines:
```
##!> assemble
  {{quotes}}
  ##!=>
  ...
##!<
```

2022-11-20 17:02 UTC, theseion commented on regex-assembly/942190.ra
> +\binto[\s+]+dumpfile\s*?{{quotes}}
Same here, as above: use a block with `{{quotes}}` as suffix.

2022-11-22 20:45 UTC, theseion commented
I've taken over this PR and need someone else to do the review.

2022-11-23 23:14 UTC, dune73 commented
I'm not totally sure, but I get the feeling that `[^\)]*?` is missing from the following 3 original items:

* `\bconnection_id\s*?\([^\)]*?`
* `\bcurrent_user\s*?\([^\)]*?`
* `\bdatabase\s*?\([^\)]*?`

2022-11-24 19:01 UTC, theseion commented
Sorry, the discussion was just between me and @53cur3M3. You're right, I should have added that to the PR.

2022-11-24 21:07 UTC, dune73 commented
No worries. That's why we do reviews after all. And now it's all documented.

2022-12-12 01:29 UTC, fzipi commented
@53cur3M3 @theseion What's next here?

2022-12-12 07:00 UTC, theseion commented
I just need a review :)

2022-12-12 10:41 UTC, fzipi approved these changes
LGTM!

2022-12-12 12:46 UTC, theseion approved these changes

2022-12-12 12:46 UTC, merged