fix(regex): fix data file for 942370
coreruleset/coreruleset pull request #2954
Opened 2022-11-03 11:42 UTC by emphazer

disassemble regex in rule 942370

2022-11-03 15:43 UTC, fzipi submitted a review, later dismissed
LGTM

2022-11-04 08:50 UTC, theseion requested changes

2022-11-04 08:50 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +  ##!=>
```suggestion
```

2022-11-04 08:50 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +[\"'`]\s*?
Use a template for ```[\"'`]```, as its repeated multiple times.

2022-11-04 08:50 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +  ##!> assemble
You are using two nested assemble blocks here, but you only need one, the outer one doesn't do anything.

2022-11-04 08:50 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +and
You can store the list of words that is repeated (or, xor, div, etc.) and reuse it, so you don't have to write it down twice.

2022-11-04 10:45 UTC, theseion requested changes
I think we need to clean up some more.

2022-11-04 10:45 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +  ##!=>
```suggestion
 ##!=>
```

2022-11-04 10:45 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +   ##!> assemble
Indent this block by four spaces, not 3.

2022-11-04 10:45 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +   ##!> assemble
```suggestion
```

2022-11-04 10:45 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +  ##!=>
```suggestion
```

2022-11-04 10:45 UTC, theseion commented on util/regexp-assemble/data/942370.data
> + ##!<
```suggestion
```

2022-11-04 10:45 UTC, theseion commented on util/regexp-assemble/data/942370.data
> +  ##!=>
```suggestion
```

2023-01-15 16:09 UTC, fzipi commented
@theseion Force pushed a new rebase version. Please double-check.

2023-01-15 19:59 UTC, theseion approved these changes

2023-01-15 20:00 UTC, theseion commented
@fzipi Added tests and fixed assembly. Please review.

2023-01-15 22:44 UTC, fzipi approved these changes
This looks awesome now. I agree that this should be part of the big documentation project for v5 maybe: knowing what the rules are testing and why.

2023-01-15 22:44 UTC, merged