fix(922110): remove possesive quantifiers
coreruleset/coreruleset pull request #2989
Opened 2022-11-10 17:23 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Fixes #2988.

2022-11-10 19:59 UTC, theseion reviewed
LGTM, but make sure to rebase onto https://github.com/coreruleset/coreruleset/pull/2984

2022-11-10 22:07 UTC, fzipi commented
Well, now that the inclusion is working, I moved the original 920600 and now both files are including the new one.

2022-11-11 07:05 UTC, theseion requested changes
Awesome!!

2022-11-11 07:05 UTC, theseion commented on util/regexp-assemble/data/include/charset-specification.data
> +##! As this specification might be use in more rules, we now
```suggestion
##! As this specification is used by several rules, we now
```

2022-11-11 17:34 UTC, theseion approved these changes

2022-11-11 17:35 UTC, merged