new test 932160-8
coreruleset/coreruleset pull request #2997
Opened 2022-11-12 23:05 UTC by dune73

New test triggering only 932160 (for status page).

2022-11-12 23:39 UTC, fzipi requested changes

2022-11-12 23:39 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
> +    desc: "Positive test: Triggering only this rule an no other one"
```suggestion
    desc: "Positive test: Triggering only this rule and no other one"
```

2022-11-12 23:39 UTC, fzipi commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
> +            method: "POST"
```suggestion
            method: "POST"
            uri: "/post"
```

2022-11-13 10:13 UTC, dune73 commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
> +    desc: "Positive test: Triggering only this rule an no other one"
thanks

2022-11-13 10:13 UTC, dune73 commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
> +            method: "POST"
thanks. fixed

2022-11-13 11:01 UTC, fzipi approved these changes

2022-11-15 11:45 UTC, merged