Util to find English words on .data
coreruleset/coreruleset pull request #3029
Opened 2022-11-25 11:01 UTC by theMiddleBlue

this could be useful for our lists, it checks English words on .data files that could lead to FPs

2022-11-25 12:01 UTC, fzipi approved these changes
It is a nice starting script!

2022-11-25 12:02 UTC, fzipi requested changes
Maybe doing a shellcheck pass first?

2022-11-25 13:19 UTC, theMiddleBlue commented
> Maybe doing a shellcheck pass first?

done

2022-11-25 17:10 UTC, theseion approved these changes

2022-11-25 17:10 UTC, theseion commented on util/fp-finder/spell.sh
> +        IS_NOT_ENGLISH=$(echo "$word" | spell | wc -l)
```suggestion
        IS_NOT_ENGLISH=$(echo "${word}" | spell | wc -l)
```

2022-11-25 17:10 UTC, theseion commented on util/fp-finder/spell.sh
> +        if [ "$IS_NOT_ENGLISH" -lt 1 ]; then
```suggestion
        if [ "${IS_NOT_ENGLISH}" -lt 1 ]; then
```

2022-11-25 17:10 UTC, theseion commented on util/fp-finder/spell.sh
> +            echo "   \`- found English word: $word"
```suggestion
            echo "   \`- found English word: ${word}"
```

2022-11-25 17:10 UTC, theseion commented on util/fp-finder/spell.sh
> +    echo "-> checking $DATAFILE_NAME"
```suggestion
    echo "-> checking ${DATAFILE_NAME}"
```

2022-11-25 17:10 UTC, theseion commented on util/fp-finder/spell.sh
> +RULES_DIR="$SCRIPT_DIR/../../rules/"
```suggestion
RULES_DIR="${SCRIPT_DIR}/../../rules/"
```

2022-11-25 17:10 UTC, theseion commented on util/fp-finder/spell.sh
> +    for word in $(grep -E '^[a-z]+$' "$datafile" | uniq | sort); do
```suggestion
    for word in $(grep -E '^[a-z]+$' "${datafile}" | uniq | sort); do
```

2022-11-25 17:11 UTC, theseion commented
Let's see what we can use it for. IMO, it should live in the toolchain at some point.

2023-04-17 16:01 UTC, dune73 approved these changes

2023-04-17 16:04 UTC, merged