New rule 942550 (PL1) JSON in SQL
coreruleset/coreruleset pull request #3055
Opened 2022-12-12 21:44 UTC by theMiddleBlue

This PR contains a new rule at PL1 that tries to catch SQL in JSON payloads not covered at PL1. For more information about the bypass technique, please refer to https://claroty.com/team82/research/js-on-security-off-abusing-json-based-sql-to-bypass-waf

2022-12-12 22:49 UTC, theMiddleBlue commented
This is a draft, I'm working to a more stricter version for SQLite and PostgreSQL in order to avoid FPs

2022-12-13 10:04 UTC, RedXanadu commented
@theMiddleBlue We don't seem to match against this example, which appears to be path-based ([original example screenshot](https://claroty-statamic-assets-cache.nyc3.digitaloceanspaces.com/containers/assets/waf_exploit.png/2c95db8fa786cdc6f17e8f0f9568c0c6.webp)):

``
curl -H 'x-crs-version: nightly' -H 'x-crs-paranoia-level: 4' -H 'x-backend: apache' -H 'x-format-output: txt-matched-rules' "https://sandbox.coreruleset.org/blah/\"\}'%20and%20data%20@>%20'\{\"a\":\"a\"\}'%20union%20select%20ASCII(s.token)%20from%20unnset(string_to_array((select%20cookie%20from%20cookie%20limit%201%20),NULL))%20s(token)--/state?sig=1&timeStamp=50"
``

We don't catch it when the attack is in the path, but we _do_ catch it when it's in `ARGS` as a query string parameter:

``
curl -H 'x-crs-version: nightly' -H 'x-crs-paranoia-level: 4' -H 'x-backend: apache' -H 'x-format-output: txt-matched-rules' "https://sandbox.coreruleset.org/blah?param=\"\}'%20and%20data%20@>%20'\{\"a\":\"a\"\}'%20union%20select%20ASCII(s.token)%20from%20unnset(string_to_array((select%20cookie%20from%20cookie%20limit%201%20),NULL))%20s(token)--/state?sig=1&timeStamp=50"
``
``
⋮
``
``
980170 PL1 Anomaly Scores: (Inbound Scores: blocking=90, detection=90, per_pl=15-56-11-8, threshold=5) - (Outbound Scores: blocking=0, detection=0, per_pl=0-0-0-0, threshold=4) - (SQLI=70, XSS=5, RFI=0, LFI=0, RCE=10, PHPI=0, HTTP=0, SESS=0)
``

2022-12-13 11:36 UTC, theMiddleBlue commented
I've changed the SQLite regex in order to avoid FPs. This rule could probably be bypassed by using other *SQL* engine functions to transform the string parameters. But other CRS rules should catch it.

https://regex101.com/r/uAPMQY/1

2022-12-13 11:44 UTC, theMiddleBlue commented
HA! the test is failing on 4 and 6 because of `%2f` ... apache always returns a 404 if `%2f` is in the URL IIRC.
@dune73 @fzipi any idea? the regex matches correctly...

https://regex101.com/r/0J5Zr0/1

2022-12-13 11:45 UTC, theMiddleBlue commented
I can remove all commend syntaxes on tests, it should fix the test problem...

2022-12-13 11:54 UTC, fzipi commented
Probably using the `data` field in tests is better than using the url?

2022-12-13 12:06 UTC, theMiddleBlue commented
ok this should cover all test cases, including the payload from @RedXanadu

2022-12-13 18:11 UTC, RedXanadu commented
Yay: tested and confirmed that it catches the path-based payload from above :smile: 

Imperva have published [some more example payloads](https://www.imperva.com/blog/abusing-json-based-sql/). Some of them we catch at PL 1, some of them we don't.

Are these concerning? Do we need to catch all of these variations, or will we be here forever?

Either way, here are the results I got:

## 1

`' or '{"key":"value"}' ? "key" --`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"key\":\"value\"}' ? \"key\" --"
```
Result: per_pl=0-36-11-13

## 2

`' or '{"name":"jack"}' ?| array['a','location']`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"name\":\"jack\"}' ?| array['a','location']"
```
Result: per_pl=0-31-11-13

## 3

`' or '{"name":"jack", "Location":"UK"}' ?& array['name','Location']`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"name\":\"jack\", \"Location\":\"UK\"}' ?& array['name','Location']"
```
Result: per_pl=0-21-19-26

## 4 :heavy_check_mark:

`' or '{"a":"b"}'::JSONB @> '{"a":"b"}'--`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"a\":\"b\"}'::JSONB @> '{\"a\":\"b\"}'--"
```
Result: per_pl=10-36-11-13 (942550 matches)

## 5

`' or '[1,2,3]'::json ->> 2 = '3'`
```
curl -v -o/dev/null 'localhost' --data "param=' or '[1,2,3]'::json ->> 2 = '3'"
```
Result: per_pl=0-36-16-13

## 6 :heavy_check_mark:

`' or '{"a":{"b":{"c":"foo"}}}'::jsonb#>'{a,b}' @> '{"c":"foo"}'::jsonb --`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"a\":{\"b\":{\"c\":\"foo\"}}}'::jsonb#>'{a,b}' @> '{\"c\":\"foo\"}'::jsonb --"
```
Result: per_pl=10-36-11-13 (942550 matches)

## 7 :heavy_check_mark: 

`' or '{"a": {"b":{"c":        "foo"}}}'::jsonb#>'{a,b}' ? 'c' --`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"a\": {\"b\":{\"c\":        \"foo\"}}}'::jsonb#>'{a,b}' ? 'c' --"
```
Result: per_pl=10-46-11-13 (942550 matches)

## 8 :heavy_check_mark:

`' or '{"a":{"b":{"c"}}}'::jsonb#>'{a,b}' ? 'c' --`
```
curl -v -o/dev/null 'localhost' --data "param=' or '{\"a\":{\"b\":{\"c\"}}}'::jsonb#>'{a,b}' ? 'c' --"
```
Result: per_pl=10-41-11-13 (942550 matches)

2022-12-13 18:34 UTC, theMiddleBlue commented
oh wow, thanks @RedXanadu this is really useful! I'm going to see if I can integrate all variations

2022-12-13 19:54 UTC, theMiddleBlue commented
added new payloads and I removed useless parts from the ra file, so the regex should be less chaotic.
moreover, it should match all payload you listed @RedXanadu (I've added a modified version of that list on the regression test file)

2022-12-13 20:03 UTC, theseion requested changes
Awesome work!

2022-12-13 20:03 UTC, theseion commented on rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> +# This rule match JSON in SQL syntax that could be used as a bypass technique
```suggestion
# This rule tries to match JSON SQL syntax that could be used as a bypass technique.
```

2022-12-13 20:03 UTC, theseion commented on regex-assembly/942550.ra
> +##!> define operators (@>|<@|\?|\?\||\?&|#>|#>>|->>|<|>|->|<-)
```suggestion
##! capture the operator in capture group
##!> define operators (@>|<@|\?|\?\||\?&|#>|#>>|->>|<|>|->|<-)
```

2022-12-13 20:03 UTC, theseion commented on tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942550.yaml
> +    desc: "JSON in SQL (ARGS)"
I suggest you use a multiline string for the description and add the payload to the description, e.g.

```
desc: |
  JSON in SQL (ARGS)
  decoded payload: OR '{"b":2}'::jsonb <@ '{"a":1, "b":2}'::jsonb
```

2022-12-13 20:05 UTC, theMiddleBlue commented
a possible false positive could be an `ARGS` value that contains the following string:

```
are '{' and '}' brackets? yes.
```

something like:

```
message=are+%27%7B%27+and+%27%7D%27+brackets%3F+yes.
```

2022-12-13 20:49 UTC, theseion approved these changes

2022-12-13 22:35 UTC, fzipi approved these changes
@theMiddleBlue This is an amazing PR. You nailed it!

2022-12-13 22:48 UTC, RedXanadu approved these changes
Confirmed that **all** of the Imperva examples are now caught at PL 1 by this new rule.

Seriously cool work @theMiddleBlue! And such a fast turn around! Plus, the regex-assemble file for this new rule is elegant and easy to read: a great example to use :rocket:

2022-12-14 01:41 UTC, merged

2022-12-16 09:36 UTC, studersi commented
Thanks a lot!

2023-01-05 00:22 UTC, bitcras approved these changes
Approve ch
Anges