Add status page test for rule 921120
coreruleset/coreruleset pull request #3083
Opened 2023-01-09 18:34 UTC by RedXanadu

PR adds a status page test for rule 921120 (a new test which only triggers this specific rule).

2023-01-09 19:15 UTC, dune73 approved these changes

2023-01-09 19:16 UTC, dune73 commented
Thank you @RedXanadu. This looks good.

Ready to merge once tests are passing.

2023-01-16 11:45 UTC, RedXanadu commented
This was a copy-paste of the Status Page test template I've been using since the Dev Retreat. I don't understand why the tests are now failing. I'll dig into this when I have some time.

2023-01-17 17:17 UTC, fzipi commented
The failing test was on the title of the PR itself. Remember we are using conventional commits. So there is a test for that. 🤷

2023-01-17 17:18 UTC, fzipi commented on tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921120.yaml
> +            uri: "/"
```suggestion
            uri: "/post"
```

2023-01-17 17:18 UTC, fzipi requested changes
I'm suggesting to use `/post` when we are posting so logs are cleaner.

2023-01-21 12:19 UTC, dune73 approved these changes

2023-01-21 12:19 UTC, dune73 commented
I am submitted your suggestion @fzipi so we can merge this. Yet GH wants you to approve first.

Please approve and merge.

2023-01-21 15:05 UTC, fzipi approved these changes

2023-01-21 15:05 UTC, merged