fix: add rce detection in request headers
coreruleset/coreruleset pull request #3132
Opened 2023-02-20 13:57 UTC by franbuehler

This PR adds 2 new rules to detect RCE in User-Agent and Referer request headers:
- 932161 at PL2 (unix commands with path)
- 932237 at PL3 (short and log unix commands without path, without prefix but with word boundary)

932237: 
I want to detect short commands like `id`, `env` and `set` in User-Agent and Referer request header.

932161: 
I want to detect unix commands with path in request headers User-Agent and Referer.

I hope I got his right and would be happy if @theseion could do a review :pray:

2023-02-20 17:01 UTC, theseion requested changes

2023-02-20 17:01 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932161.yaml
> +---
Add the same tests for Referer.

2023-02-20 17:01 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +---
Add the same tests for Referer.

2023-02-20 19:48 UTC, franbuehler commented on regex-assembly/932237.ra
> +##!> include unix-shell-4andup-with-params
Ok, thank you.

2023-02-20 19:50 UTC, franbuehler commented
Thank you very much for your review @theseion 
I don't know why the no_log_contains tests are failing.
Is it possible that the tests are using "User-Agent: OWASP ModSecurity Core Rule Set" even if I set them with CRS in the tests? -> they contain the set that triggers rule 932237 (set)

2023-02-20 20:45 UTC, franbuehler commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# Regular expression generated from regex-assembly/932237.ra.
Added

2023-02-20 20:46 UTC, franbuehler commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932161.yaml
> +---
Added

2023-02-20 20:46 UTC, franbuehler commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +---
Added

2023-02-20 21:12 UTC, theseion commented
There are two separate issues we need to fix:
1. disable matching against `REQUEST_HEADERS` for internal go-ftw requests (already solved, will open a PR)
2. figure out a way to deal with the default `User-Agent` header we use in tests; we might have to change it.

I'll look into this tomorrow.

2023-02-20 21:31 UTC, dune73 commented
You mean we overwrite the header set in the test - and this did not cause any problems so far?

2023-02-21 00:13 UTC, fzipi commented
Looks like we are matching this now:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/3012076/220216079-743300fe-9a45-486e-9bca-9fb7c26f2e07.png">

2023-02-21 06:07 UTC, theseion commented
Exactly. I propose to change the default user agent string in the tests to "OWASP CRS test agent". That change could be part of this PR.

2023-02-21 11:19 UTC, franbuehler commented
Please let me know when I have to change something in my tests.

2023-02-21 19:13 UTC, theseion commented
@dune73 @fzipi do you agree to the proposed change?

@franbuehler, in case they agree, you need to change _all_ occurrences of `User-Agent: OWASP ModSecurity Core Rule Set` to `User-Agent: OWASP CRS test agent`. That change affects _all_ rules.

2023-02-22 05:00 UTC, fzipi commented
You meant all tests, right?

2023-02-22 06:13 UTC, theseion commented
Yes, all tests of all rules.

2023-02-22 07:28 UTC, franbuehler commented
Oooook :-) So I wait for @dune73 and @fzipi decision and if they agree, I'll change the UA of _all_ tests of _all_ rules in this PR here or should I open a new PR for that?

2023-02-22 07:31 UTC, theseion commented
Yes. It would be cleaner to have a separate PR.

> On Wednesday, Feb 22, 2023 at 8:29 AM, Franziska Bühler ***@***.*** ***@***.***)> wrote:
>
>
>
>
> Oooook :-) So I wait for @dune73 (https://github.com/dune73) and @fzipi (https://github.com/fzipi) decision and if they agree, I'll change the UA of all tests of all rules in this PR here or should I open a new PR for that?
>
>
> —
> Reply to this email directly, view it on GitHub (https://github.com/coreruleset/coreruleset/pull/3132#issuecomment-1439550093), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AAB5GVYMEZFTI5GWMKICRFLWYW53ZANCNFSM6AAAAAAVB5D7K4).
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>
>
>

2023-02-22 08:52 UTC, dune73 commented
I think it is not 100% clear what we are deciding here.

What I understand:
* This PR here will break every CRS test.
* There is going to be a new default UA for all CRS tests: `User-Agent: OWASP CRS test agent`. There is going to be a separate PR to implement this. We'll probably fast track that.
* Once the additional PR has been merged, this PR needs to adopt the new default UA, it can then be merged.

If that understanding is correct, then I agree.

2023-02-22 15:43 UTC, fzipi commented
https://github.com/coreruleset/coreruleset/pull/3136 is the user-agent test change.

2023-02-22 18:02 UTC, theseion approved these changes

2023-02-22 18:03 UTC, theseion commented
Would it make sense to match 932237 at PL2 instead of PL3?

2023-02-22 20:29 UTC, franbuehler commented
@dune73 : yes, correct. I already fixed the tests in this PR here, but the regression tests are still failing.

@theseion : yes, we can move rule 932237 to PL3. I chose PL3 because the regexp is very similar to 932236, but 932237 is even stricter (without prefixes and arguments). If we decide to move 932237 to PL2, would it make sense to remove UA and referer from 932236 again?
Do you know why the tests are still failing? Is there something else I have to change?

2023-02-22 20:34 UTC, dune73 commented
I personally have a knack for PL3, but nothing wrong if you prefer PL2.

2023-02-22 20:53 UTC, theseion commented
I don't care. Just asking.

2023-02-22 21:04 UTC, dune73 commented
Still failing. Hmm...

2023-02-22 21:09 UTC, theseion commented
@fzipi missed some tests :) opening PR now.

2023-02-22 21:14 UTC, theseion commented
In addition, we need a new release of the container images to prevent matching of the log marker request. I don't know how to do that. @fzipi, could you?

2023-02-23 00:22 UTC, fzipi commented
> In addition, we need a new release of the container images to prevent matching of the log marker request. I don't know how to do that. @fzipi, could you?

Ok, now I understand:
```
Apache-Error: [file "apache2_util.c"] [line 275] [level 3] [client 172.18.0.1] ModSecurity: Warning. Pattern match "(?i)\\\\\\\\b(?:7z[ar]?|a(?:b|pt(?:-get)?|r(?:[jp]|ch[\\\\\\\\s\\\\\\\\v<>]|ia2c)?|s(?:h|cii(?:-xfr|85)|pell)?|t(?:obm)?|w[ks]|dduser|getty|l(?:ias|pine)[\\\\\\\\s\\\\\\\\v<>]|nsible-playbook)|b(?:z(?:z|c(?:at|mp)|diff|e(?:grep|xe)|f?grep|ip2|less|more)|a(?:s(?:e(?:32|64|nc)|h)|tch ..." at REQUEST_HEADERS:User-Agent. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf"] [line "1377"] [id "932237"] [msg "Remote Command Execution: Unix Shell Code Found in REQUEST_HEADERS"] [data "Matched Data: go found within REQUEST_HEADERS:User-Agent: go-ftw test agent"] [severity "CRITICAL"] [ver "OWASP_CRS/4.0.0-rc1"] [tag "modsecurity"] [tag "application-multi"] [tag "language-shell"] [tag "platform-unix"] [tag "attack-rce"] [tag "paranoia-level/3"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/88"] [tag "PCI/6.5.2"] [hostname "localhost"] [uri "/status/200"] [unique_id "Y_aCijGpVgNdTsFOZynARgAAAEc"]
```

2023-02-23 20:22 UTC, theseion approved these changes
LGTM

2023-02-23 20:27 UTC, franbuehler commented
Thank you!! I'll merge it then.

2023-02-23 20:27 UTC, merged