fix: fixes a few invalid uri for 934130 and 934131 tests
coreruleset/coreruleset pull request #3133
Opened 2023-02-21 11:33 UTC by M4tteoP

Hi!
Sibling of https://github.com/coreruleset/coreruleset/pull/2880. There are some positive tests in which the `uri` is not starting with a `/`. Go server and Envoy deny these requests with a `400`, therefore tests fail and the real payload that we are trying to analyze is not checked.
The tests are about JavaScript prototype pollution injection attempts, I don't think that it was intended to try to specs/rfcs regarding the path format.
Thanks!

2023-02-21 12:37 UTC, fzipi requested changes
Maybe changing it to `/get?...` is better, so _httpbin_ doesn't show additional errors in the logs while running the tests?

2023-02-21 13:14 UTC, M4tteoP commented
Done, added it also the other tests in the `934130` file which were already `/?`.

2023-02-21 13:15 UTC, fzipi approved these changes
Awesome, thanks!

2023-02-22 10:20 UTC, dune73 commented
Looks good. Thanks. Merging now.

2023-02-22 10:20 UTC, merged