doc: Rewrite issue templates for false positives and false negatives
coreruleset/coreruleset pull request #3135
Opened 2023-02-22 08:44 UTC by dune73

I have rewritten the two issue templates from scratch. I thought it was necessary to make it clearer what we really need.

2023-02-22 15:33 UTC, fzipi submitted a review, later dismissed
Way better, thanks.

2023-02-22 18:25 UTC, theseion requested changes
Very good, thanks!

2023-02-22 18:25 UTC, theseion commented on .github/ISSUE_TEMPLATE/01_false-positive.md
> +depends on the provider. Please refer to the documentation.
```suggestion
depends on the provider. Please refer to their documentation.
```

2023-02-22 18:25 UTC, theseion commented on .github/ISSUE_TEMPLATE/01_false-positive.md
> +If you can not submit a curl call nor log files or a payload to reproduce
```suggestion
If you cannot submit neither curl call nor log files nor a payload to reproduce
```

2023-02-22 18:25 UTC, theseion commented on .github/ISSUE_TEMPLATE/01_false-positive.md
> +the information we need to help you.
```suggestion
get access to the information we need to help you.
```

2023-02-22 18:25 UTC, theseion commented on .github/ISSUE_TEMPLATE/01_false-positive.md
> +* Web Server and version or cloud provider / CDN (e.g., apache 2.4.54):
```suggestion
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54):
```

2023-02-22 18:25 UTC, theseion commented on .github/ISSUE_TEMPLATE/02_false-negative.md
>  name: 'False negative'
Same changes as in the other template.

2023-02-22 21:03 UTC, theseion approved these changes

2023-02-24 09:27 UTC, dune73 commented
@RedXanadu Are you OK with this wording? If yes, please merge.

2023-03-13 14:15 UTC, RedXanadu commented
Sorry for the delay in reviewing this…

@dune73 This looks good! The expanded guidance is clearer.

One comment I would make, from a _Dev on Duty_ perspective: if someone is reporting an FP then logs are a "must have", while a curl call is only a "nice to have". It's probably unlikely that users will start submitting reports with no logs and only curl calls, but it's something to think about if that situation does start to happen (I don't think it will, as it takes much more time to craft a curl call than to copy-paste log lines).

2023-03-13 14:16 UTC, RedXanadu approved these changes
Merging now.

2023-03-13 14:17 UTC, merged

2023-03-17 08:33 UTC, dune73 commented
I see your point on the dev-on-duty needs, @RedXanadu. Let's keep an eye on this.