fix(config): format crs-setup.conf.example
coreruleset/coreruleset pull request #3157
Opened 2023-03-12 13:23 UTC by airween

This PR formats `crs-setup.conf.example` file:
* puts the actions in the correct order
* set the correct indentations

This is necessary if we want to process the `crs-setup.conf.example` with all commented `SecRule`'s and `SecAction`'s to fix #3141 without adding an extra rule.

If we don't want to allow these modifications (in this PR), the other possible solution is that we ignore checking of indentations and order of actions in that file.

I prefer this solution.

The next PR will contain that `rules-check.py` script process `crs-setup.conf.example` without comments in case of `SecRule` and `SecAction` lines (and next ones).

2023-03-12 20:43 UTC, fzipi approved these changes
This makes total sense to me.

2023-03-13 16:40 UTC, theseion requested changes

2023-03-13 16:40 UTC, theseion commented on crs-setup.conf.example
> +#SecRuleUpdateActionById 901450 "nolog"
This line isn't explained in this file. The comment is in `REQUEST-901-INITIALIZATION.conf`:
```
# If a request is allowed to pass without being checked by the CRS, there is no
# entry in the audit log (for performance reasons), but an error log entry is
# being written.  If you want to disable the error log entry, then issue the
# following directive somewhere after the inclusion of the CRS
# (E.g., RESPONSE-999-EXCEPTIONS.conf).
```

That comment should be moved here, IMO. @dune73?

2023-03-13 16:41 UTC, theseion approved these changes

2023-03-15 16:41 UTC, merged