feat(windows): update windows commands list
coreruleset/coreruleset pull request #3170
Opened 2023-03-19 16:00 UTC by franbuehler

This PR resolves issue #2671 by updating the Windows commands.
Rule 932115 was moved to new rule 932380.

2023-03-19 16:05 UTC, franbuehler commented
Tests are failing because rule 932115 was moved to new rule 932380:

`04:02:26 FTL ../../crs-toolchain/crs-toolchain/cmd/regex_compare.go:213 > Failed to find rule 932115, chain offset, 0 in /home/runner/work/coreruleset/coreruleset/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf component=cmd`

2023-03-20 20:51 UTC, theseion commented
Lint is complaining because you still have a regex-assembly file for 932115.

2023-03-20 20:55 UTC, franbuehler commented
Ahhh, thank you! I'll remove it and test again. Thank you!

2023-04-17 15:34 UTC, dune73 commented
This is delayed until after your holidays, I presume @franbuehler?

2023-04-24 09:37 UTC, franbuehler commented
After the latest rebase the tests are successful!
This PR is ready for a review.

2023-04-25 05:01 UTC, theseion requested changes

2023-04-25 05:01 UTC, theseion commented on regex-assembly/932380.ra
> +    active
I think you need to exclude some of these entries to avoid FPs at PL 1. For example, `active`, `add`, `append`, `where`.
To avoid issues when updating in the future, it might be best to create a separate list with these exclusions and then use `include-except` to include the list of command words and exclude those words you don't want.

2023-04-29 10:14 UTC, franbuehler commented on regex-assembly/932380.ra
> +    active
I need your advice here.

I generated two exclusion files now.
1. One was generated manually: I looked through the commands of [932380.ra](https://github.com/coreruleset/coreruleset/pull/3170/files/4b4862628736250ffc45a1d035fd491a67b760cc#diff-98b51f9411c6a49005bbea8f109f9679d77620ce38e6ca0858d183983b37fb4a) and decided which word is prone to fp.
2. The other list was generated by @theMiddleBlue's script https://github.com/coreruleset/coreruleset/blob/v4.0/dev/util/fp-finder/spell.sh. I had to extend it a bit to pass the ra file as a command line argument and to delete leading spaces because the ra files are in a different format.

This generated exclusion lists differs a bit (more words in it) from the manually generated list but I still think it's better to have an automatically generated exclusion list.

So my plan would be:
1. open a PR that extends @theMiddleBlue's script (but I need some help here, I write ugly scripts).
2. use this extended spell.sh script to generate the exclusion list for this PR here.

Is this a good plan? Or what do you think?

2023-04-30 14:24 UTC, theseion commented on regex-assembly/932380.ra
> +    active
Sounds great!

2023-06-07 16:57 UTC, franbuehler commented on regex-assembly/932380.ra
> +    active
Finally opened a PR for that: #3233

2023-06-07 19:34 UTC, franbuehler commented
The tests are failing because the command `sort` is now excluded:

- [sort in exclude list](https://github.com/coreruleset/coreruleset/pull/3170/files#diff-45bad221071474830d53633af5ba1574bf36e4bc9b87a3e91f3e6c3531d35789R83)
- [sort in tests](https://github.com/coreruleset/coreruleset/pull/3170/files#diff-0ccbe77f8ef18020a6af50de0b6ac7d24b3919b58b08363eb05ab189d2ee6687R10)

Is that ok??

2023-06-08 04:45 UTC, theseion commented on regex-assembly/932380.ra
> +    active
Yes, I think that's fine. Just change the test to use a different command.

2023-06-08 19:29 UTC, theseion requested changes

2023-06-11 10:40 UTC, franbuehler commented on regex-assembly/932380.ra
Thank you! Done.

2023-06-11 14:39 UTC, theseion commented
Let's wait until the other PR ist merged.

2023-06-15 15:08 UTC, dune73 commented
That was a frenzy of changes. What is left to do here before we can merge?

2023-06-15 20:12 UTC, franbuehler commented
In my opinion it's ready to be merged. Let's wait for the final review and approval by @theseion.

2023-06-18 19:02 UTC, theseion requested changes

2023-06-18 19:02 UTC, theseion commented on regex-assembly/932380.ra
> +##! Note: the quoting prefixes are part of the command prefixes, except for ^
This command belongs in `windows-commands-prefix.ra`.

2023-07-04 09:10 UTC, franbuehler commented on regex-assembly/932380.ra
> +##! Note: the quoting prefixes are part of the command prefixes, except for ^
Done

2023-07-09 19:48 UTC, theseion commented on regex-assembly/include/windows-commands-prefix.ra
> +##! Command words, in this case, must folow the prefix.
Yes, you're right. Prefixes and suffixes are local to their file. I did that on purpose. We'll have to live with the duplicates for now. Sorry for the confusion.

2023-07-09 19:50 UTC, theseion approved these changes

2023-07-09 19:51 UTC, theseion commented
LGTM

2023-07-12 16:28 UTC, merged