fix: exclude well known user agents from unix commands
coreruleset/coreruleset pull request #3190
Opened 2023-04-04 20:13 UTC by theseion

User agents like `curl` and `wget` currently lead to false positives because they are valid in `User-Agent` headers.
This commit moves the matching against the `User-Agent` header of 932236 into a separate rule 932238, so that words like `curl` and `wget` are still treated as attacks in other payloads but are excluded for the `User-Agent` header checks.

In addition, the well known user agents are also excluded from rule 932237, which only matches against `Referer` and `User-Agent`. An additional rule was omitted for simplicities sake.

2023-04-05 05:55 UTC, emphazer commented
Hey Max, that looks like a great fix!
i will check it out!
thanks!

2023-04-16 13:37 UTC, theseion commented
I've rewritten this PR to use a more flexible approach. I didn't like that the exclusion also affected other targets.

2023-04-16 13:37 UTC, theseion commented
@dune73 @emphazer I'd appreciate it if you would take another look at this one.

2023-04-16 14:01 UTC, theseion commented
@airween I've tried to fix the comment rule of `secrule-parser` to allow comments before a chained rule but didn't succeed. Could you help me out?

2023-04-17 12:20 UTC, airween commented
This is just a quick review, and gives a workaround. We should discuss the syntax, because [there isn't any](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/CONTRIBUTING.md#general-formatting-guidelines-for-rules-contributions) restriction for comments between parts of chained rules.

First of all, this modification fixes the [secrules-parser](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/.github/workflows/lint.yaml#L36) error:

```diff
1331,1334c1331,1334
<     # Regular expression generated from regex-assembly/932239-chain1.ra.
<     # To update the regular expression run the following shell script
<     # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
<     #   crs-toolchain regex update 932239-chain1
---
> # Regular expression generated from regex-assembly/932239-chain1.ra.
> # To update the regular expression run the following shell script
> # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
> #   crs-toolchain regex update 932239-chain1
1545,1548c1545,1548
<     # Regular expression generated from regex-assembly/932238-chain1.ra.
<     # To update the regular expression run the following shell script
<     # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
<     #   crs-toolchain regex update 932238-chain1
---
> # Regular expression generated from regex-assembly/932238-chain1.ra.
> # To update the regular expression run the following shell script
> # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
> #   crs-toolchain regex update 932238-chain1
```

As you can see, the solution is simply remove the white spaces from the beginning of comment lines.

This will prevent the next possible issue: [rules-check.py](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/.github/workflows/lint.yaml#L42) would also triggered with this syntax.

The reason is simple: rules-check.py has a test case, [namely](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/util/crs-rules-check#test-4---wrong-indentation) it checks the indentation. That [uses](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/util/crs-rules-check/rules-check.py#L766-L767) [msc_pyparser](https://github.com/digitalwave/msc_pyparser)'s `MSCWriter` class, which writes the comments **without** any indentation.

If we want to allow the indents (rather we would expect them) before comments which are between parts of chained rules, we have to modified the msc_pyparser too.

This would not be a complicated modification IMHO, but I started to play with [secrules_parser](https://github.com/coreruleset/secrules_parsing/blob/master/src/secrules_parsing/model/secrules.tx#L161), but actually I couldn't fix this issue yet.

(This is what I tried:
```diff
@@ -157,8 +157,8 @@ Transformation:
 
         
 /* This is to take rule continuations (\\n) as comments */    
-Comment[ws='\t ']:
-    /\\\n|^\#.*$/;
+Comment[ws='\t \n']:
+    /\\\n|^( |\t)*\#.*$/;
```
so I tried to add an optional whites space block before the comment; Unfortunately I don't see why isn't that works.)

2023-04-17 15:26 UTC, dune73 commented
Went over it again. Still did not check out the tests in detail, but it looks good to me (outside of the test failing, obviously).

2023-04-17 18:27 UTC, airween commented
> Thanks @airween, I tried the same but didn't get it working. I'll just outdent the comments then.

Hmm... it's very weird...

```
$ diff REQUEST-932-APPLICATION-ATTACK-RCE_3190.conf REQUEST-932-APPLICATION-ATTACK-RCE_3190_2.conf 
1331,1334c1331,1334
<     # Regular expression generated from regex-assembly/932239-chain1.ra.
<     # To update the regular expression run the following shell script
<     # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
<     #   crs-toolchain regex update 932239-chain1
---
> # Regular expression generated from regex-assembly/932239-chain1.ra.
> # To update the regular expression run the following shell script
> # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
> #   crs-toolchain regex update 932239-chain1
1545,1548c1545,1548
<     # Regular expression generated from regex-assembly/932238-chain1.ra.
<     # To update the regular expression run the following shell script
<     # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
<     #   crs-toolchain regex update 932238-chain1
---
> # Regular expression generated from regex-assembly/932238-chain1.ra.
> # To update the regular expression run the following shell script
> # (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
> #   crs-toolchain regex update 932238-chain1

$ poetry run secrules-parser -c -f REQUEST-932-APPLICATION-ATTACK-RCE_3190.conf 
Syntax invalid: Syntax error in line 1331 col 5: Expected 'SecAction' or 'SecRuleScript' or 'SecRule' or 'SecMarker' or 'SecComponentSignature' or 'SecRuleRemoveById' or 'SecRuleRemoveBytag' or EOF at position /home/airween/src/secrules_parsing/REQUEST-932-APPLICATION-ATTACK-RCE_3190.conf:(1331, 5) => 'hain"     *# Regular '.

$ poetry run secrules-parser -c -f REQUEST-932-APPLICATION-ATTACK-RCE_3190_2.conf 
Syntax OK: REQUEST-932-APPLICATION-ATTACK-RCE_3190_2.conf
```

Of course, this works without any modification of `secrule_parsing`.

2023-04-17 18:58 UTC, airween commented
> I tried the same but didn't get it working. I'll just outdent the comments then.

But now the test has passed. So it works, isn't it?

2023-04-23 18:01 UTC, theseion commented
I'd love some feedback on this one. @emphazer or @theMiddleBlue maybe?

2023-04-23 20:13 UTC, emphazer commented
@theseion i already spend friday some time with this PR. I will give you feedback during the week ;-)

2023-04-24 04:57 UTC, theseion commented
Awesome, thank you!

2023-04-24 23:56 UTC, theMiddleBlue requested changes

2023-04-24 23:56 UTC, theMiddleBlue commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_HEADERS:User-Agent "!@pmFromFile benign-user-agents.data" \
Same here, possible rule bypass

2023-04-24 23:56 UTC, theMiddleBlue commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +    t:none,t:cmdLine,t:normalizePath,\
I think you don't want `t:normalizePath` on User-Agent

2023-04-25 05:32 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_HEADERS:User-Agent "!@pmFromFile benign-user-agents.data" \
Yes, you are right of course. IMO, this rule is just there to filter some basic automated attacks. If you want the real deal you'll need to enable PL 3 probably. So the question is, would users benefit from this rule, even if it is trivial to bypass?

2023-04-25 19:54 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_HEADERS:User-Agent "!@pmFromFile benign-user-agents.data" \
> Can we replace the first rule of the chain by using a regex? Something like @rx ^curl/[0-9.]+$

Yes. Maybe that's better.

> I see more problems with the unix-shell-* list. We're doing it as is to prevent something like system($useragent) in the protected application, but I think this is not something we can do at PL1 and PL2. It leads to a ton of FP and FN.

Do you mean in general or for this rule in particular? We had the unix-shell* lists before and they (sort of) worked...

2023-04-25 20:25 UTC, theMiddleBlue commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_HEADERS:User-Agent "!@pmFromFile benign-user-agents.data" \
in general, I think they worked well with an acceptable FP level until we start to match against UA and Referer request headers. This is just my opinion, I can continue to exclude UA and Referer from those rules. I'm just worried that using 4.0 at PL2 will be hard, if not impossible, for integrators.

2023-04-26 16:11 UTC, dune73 commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +SecRule REQUEST_HEADERS:User-Agent "!@pmFromFile benign-user-agents.data" \
Can you guys prepare this question for the chat on Monday? I think it deserves a thorough discussion.

2023-08-10 08:48 UTC, franbuehler reviewed
There are some open issues but I think the idea behind this PR makes sense!

2023-08-14 12:03 UTC, RedXanadu commented
I'm not sure the chain rule approach is a good idea, for the reasons already discussed by others.

I thought there was a crs-toolchain function to exclude unwanted keywords? Let's use that?

Or can we add a PL 3 rule, something like "Automated tooling detected", which picks up curl, wget, Go HTTP library UA, Perl HTTP library UA, etc. etc. and then CRS installers can switch off the rule if they want to allow such tooling to be used?

Sorry if this is too simplistic :sweat_smile: Maybe I'm missing something.

2023-09-21 04:57 UTC, theseion commented
As discussed, this approach doesn't work.

2023-09-21 04:57 UTC, closed without merging

2023-09-21 08:52 UTC, RedXanadu commented
For future reference: this was picked up in #3189, go there for further discussion (correct me if I'm wrong).