feat(941220): add regexp-assembly for deconstructed regex
coreruleset/coreruleset pull request #3263
Opened 2023-07-19 09:50 UTC by fzipi

Complements #3262.

Fixes #2580.

We can probably create an include file with the "script" part, but I don't know if it makes too much sense.

2023-07-19 11:49 UTC, RedXanadu commented
The documentation here is great :smile: Hopefully we can bring all the regex assemble files up to this level.

2023-07-20 18:05 UTC, theseion requested changes
I'll wait for you to make the changes to the other rule. The comments there apply here as well.

2023-07-20 18:05 UTC, theseion commented on regex-assembly/941220.ra
> +##!+ i
Move to after the rule comment.

2023-07-20 18:05 UTC, theseion commented on regex-assembly/941220.ra
> +##!> define whitespaces \t|\n|\r
```suggestion
##!> define whitespaces [\t\n\r]
```

2023-07-20 18:06 UTC, theseion commented
I don't think moving the `script` part (or individual characters) to an include file is necessary. We can discuss it when we need it a third time.

2023-08-05 08:31 UTC, fzipi commented
Updated similar to the other rule.

2023-08-07 08:57 UTC, theseion approved these changes

2023-08-07 09:07 UTC, merged