feat: replace restricted-uploads.data with restricted-files.data
coreruleset/coreruleset pull request #3282
Opened 2023-08-16 19:07 UTC by theseion

restricted-uploads.data was a subset of restricted-files.data. restricted-files.data includes many more paths than restricted-uploads.data but is more restrictive.

Fixes #2644

2023-08-23 18:39 UTC, theseion commented on rules/restricted-upload.data
> +0
Those are process IDs from `/proc/<ID>`. I'll remove those as they would very likely lead to many false positives.

2023-08-23 18:44 UTC, theseion commented on rules/restricted-upload.data
> +# sed -i -e '7,$d' rules/restricted-upload.data && \
I want to retain the header and then append the output.

2023-08-31 20:42 UTC, dune73 requested changes
See comment in "conversation"

2023-09-07 18:47 UTC, theseion commented
Good catch. I've extended the script to run the source list through spell.sh. This does not address all of the items in your list but at least the most obvious ones. Do you think that's enough?

2023-09-08 09:56 UTC, dune73 commented
Thanks.

We're now down to the following keywords, that might lead to FPs based on my previous assessment:

```
	Dockerfile
	asound
	config
	cpuinfo
	crypto
	filesystems
	hypervisor
	key-users
	meminfo
	misc
	zoneinfo
```

We might get away with most of these, but we can not add `crypto` and `misc` to a PL1 rule. `config` is a bit of an edge case for me. Using `crypto` in a filename should be legitimate, `misc` too of course. I think `config` falls into the same category: Uploading a file like `CNC-configuration.xxx` seems perfectly natural and should not lead to a FP, no matter it may resemble a critical application server configuration file that is being replaced during an ongoing attack.

I think we need to add at least these 3 terms to `./util/fp-finder/english-extended.txt` and remove them from this PR.

2023-09-08 14:02 UTC, theseion commented
Done.

2023-09-08 14:13 UTC, dune73 approved these changes
OK, cool. Thanks.

This is a major expansion of the detection for rule 932180. This is potentially adding FPs too. Adding this here for the record.

Merging now.

2023-09-08 14:13 UTC, merged