Added description for rule 942450
coreruleset/coreruleset pull request #3283
Opened 2023-08-21 17:03 UTC by Xhoenix

Description for hex evasion detection rule

2023-08-23 19:26 UTC, theseion requested changes

2023-08-23 19:26 UTC, theseion commented on rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> +# (?i:\b0x[a-f\d]{3,}) #match any 3 or more hex bytes after "0x", together forming a hexadecimal payload(e.g 0xf00, 0xf00d and so on)
```suggestion
# (?i:\b0x[a-f\d]{3,}) will match any 3 or more hex bytes after "0x", together forming a hexadecimal payload(e.g 0xf00, 0xf00d and so on)
```

2023-08-24 06:05 UTC, theseion approved these changes

2023-08-24 06:05 UTC, merged

2023-08-24 06:06 UTC, theseion commented
Thanks @Xhoenix.

2023-08-24 11:58 UTC, dune73 commented
Good stuff.

2023-08-24 12:15 UTC, RedXanadu commented
Sorry for the delay, I didn't get around to merging this one in time as promised :laughing:

@Xhoenix Was this your first PR? If so, we'll need to add you to the list of contributors :tada:

2023-08-24 12:24 UTC, dune73 commented
Far from it.

```
$ git log | grep -e "Merge pull request.*Xhoenix"
    Merge pull request #3219 from Xhoenix/v4.0/dev
    Merge pull request #3215 from Xhoenix/v4.0/dev
    Merge pull request #3214 from Xhoenix/v4.0/dev
    Merge pull request #3213 from Xhoenix/v4.0/dev
    Merge pull request #3212 from Xhoenix/v4.0/dev
```