Moves FP prone phrase `file size is` to PL2
coreruleset/coreruleset pull request #3314
Opened 2023-09-18 19:28 UTC by M4tteoP

`File size is` phrase leads to false positives. [It has been agreed](https://github.com/coreruleset/coreruleset/issues/3279#issuecomment-1724191613) to move it from `rules/php-errors.data` to `rules/php-errors-pl2.data`. Now it will be matched by `953101`, at PL2. 

Closes https://github.com/coreruleset/coreruleset/issues/3304

2023-09-18 19:39 UTC, theseion requested changes
There's no automation for the PL 2 stuff. Can you add tests for the two rules (negative ones to PL1, positive to PL2) so that we catch changes when we update the list?

2023-09-19 06:46 UTC, theseion requested changes
Awesome, thanks! Could you add tests for the other three items at PL2 as well?

2023-09-19 08:25 UTC, M4tteoP commented
> Could you add tests for the other three items at PL2 as well?

Ups, sounds very right, done, thank you

2023-09-19 08:34 UTC, theseion approved these changes

2023-09-19 08:35 UTC, merged