fix: remove user-agents from rules 932236 and 932237
coreruleset/coreruleset pull request #3318
Opened 2023-09-23 19:26 UTC by franbuehler

This PR resolves #3189 by:
* adding a new PL2 rule 932239 that is a copy of rule 932236 but only checks request headers referer and user-agent and excludes know user-agents
* removing the request headers user-agent and referer from rule 932236
* exlcuding the know user-agents from rule 932237

This PR also adds tests for 932239 and removes user-agent and referer header tests from 932236.

2023-09-28 14:11 UTC, dune73 commented
I think this is good to go. Another pair of eyes welcome, though.

2023-09-28 14:12 UTC, dune73 submitted a review, later dismissed

2023-09-28 19:15 UTC, theseion commented
I'll probably get around to this on Saturday.

2023-09-30 11:50 UTC, theseion requested changes

2023-09-30 11:50 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-pl2-useragents.ra
Creating this file shouldn't be necessary. I'd rather extend the toolchain to allow for more than one exclusion file than having to maintain additional files like this one. Let me make that change first, shouldn't be a big deal.

2023-09-30 11:50 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-pl2.ra
> +##! If this list is changed, please also update the list unix-shell-fps-pl2-useragents.ra.
Will not be necessary with the update to the toolchain.

2023-09-30 11:50 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents.ra
This file should have the suffix `-with-params`, as the others that use the suffixes.

2023-09-30 11:50 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents.ra
> +##! in rules checking for RCE in user-agent and referer request header.
```suggestion
##! in rules checking for RCE in User-Agent and Referer request header.
```

2023-09-30 11:50 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents.ra
> +##! If this list is changed, please also update the list unix-shell-fps-pl2-useragents.ra.
Will not be necessary with the change to the toolchain.

2023-09-30 11:50 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents.ra
> +cpan
It would be great if you could add a comment for each entry. For example, looking at the list I don't know why `links`, `snap`, or `w3m` should be in there.

2023-09-30 11:50 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# This sibling detects Unix RCE in request headers referer and user-agent.
```suggestion
# This sibling detects Unix RCE in request headers Referer and User-Agent.
```

2023-09-30 14:26 UTC, franbuehler commented on regex-assembly/exclude/unix-shell-fps-pl2-useragents.ra
Yes! That was exactly the problem I had. So I had to create this file with the combination of the two files.

2023-10-01 11:43 UTC, franbuehler commented
This PR can be merged after the new release of crs-toolchain (PR https://github.com/coreruleset/crs-toolchain/pull/91).
The pipeline is currenty failing.

2023-10-02 05:35 UTC, theseion requested changes

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-pl2.ra
> +##!
```suggestion
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent Links (2.3pre1; Linux 2.6.38-8-generic x86_64; 170x48)
```suggestion
# Links browser (https://en.wikipedia.org/wiki/Links_(web_browser)): Links (2.3pre1; Linux 2.6.38-8-generic x86_64; 170x48)
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent curl
```suggestion
# curl (https://curl.se): curl/8.1.2
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent Cpanel-HTTP-Client/1.0
```suggestion
# CPanel client (https://cpanel.net): Cpanel-HTTP-Client/1.0
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent python-requests/2.31.0 and Python-urllib/3.9
```suggestion
# Requests (https://docs.python-requests.org/en/latest/index.html): python-requests/2.31.0
# urllib (https://docs.python.org/3/library/urllib.html): Python-urllib/3.9
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent Snap URL Preview Service; bot; snapchat; https://developers.snap.com/robots
```suggestion
# Snapchat URL Preview Service (https://developers.snap.com/robots): Snap URL Preview Service; bot; snapchat; https://developers.snap.com/robots
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent w3m/0.5.1
```suggestion
# w3m browser (https://en.wikipedia.org/wiki/W3m): w3m/0.5.1
```

2023-10-02 05:35 UTC, theseion commented on regex-assembly/exclude/unix-shell-fps-useragents-with-params.ra
> +# User-Agent wget
```suggestion
# wget (https://www.gnu.org/software/wget/): wget
```

2023-10-02 05:35 UTC, franbuehler commented
I added your suggestions and commited your changes. The pipeline was successful because of the new crs-toolchain. Could you please do a review again, @theseion ?

2023-10-02 05:36 UTC, theseion commented
Already done ;)

2023-10-02 16:49 UTC, theseion approved these changes

2023-10-02 16:50 UTC, merged

2023-10-04 09:08 UTC, dune73 commented
Sweet to see this solved for good.