feat: added PostgreSQL error message
coreruleset/coreruleset pull request #3336
Opened 2023-10-16 10:19 UTC by Xhoenix

Source: https://portswigger.net/web-security/sql-injection/cheat-sheet

2023-10-16 18:18 UTC, theseion requested changes
Great additions, thanks!

Please add at least one test for each of the new entries and document the source for each entry (the page you linked to does not list the error messages you added, for example).

2023-10-16 18:26 UTC, theseion commented
I don't see any changes to test files in your PR.

<img width="324" alt="Screenshot 2023-10-16 at 20 25 49" src="https://github.com/coreruleset/coreruleset/assets/250711/16e2dd15-e0a6-48e4-9301-3712cebcbd45">

2023-10-17 08:19 UTC, Xhoenix commented
@theseion is a test really necessary? I just checked @azurit has created the tests with something like this:-

https://github.com/coreruleset/coreruleset/blob/249a0b7aa4cb18f50577f47bdb38d5836044524b/tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951230.yaml#L25-L27

As we're checking the response body for the desired error messages, it's just a simple copy/paste of the rules created by @azurit

2023-10-17 17:38 UTC, theseion commented
In my opinion yes, the tests are necessary. We have too little test coverage. I know that it's a little bothersome but doing this kind of work pays off in the long run. Not only that, we will be able to reuse tests for things like performance measurements.

2023-10-19 05:07 UTC, theseion requested changes
That looks pretty good, thanks. Just a bit of clean up and a test fix.

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
> +            data: "[match sql-errors.data]the used select statements have different number of columns[/match]: ERROR:  invalid input syntax for type integer"
```suggestion
            data: "[match sql-errors.data]the used select statements have different number of columns[/match]: ERROR:  invalid input syntax for integer"
```

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
> +  author: "azurit and Xhoenix"
```suggestion
  author: "azurit, Xhoenix"
```

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951230.yaml
> +  author: "azurit and Xhoenix"
```suggestion
  author: "azurit, Xhoenix"
```

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951220.yaml
> +  author: "azurit and Xhoenix"
```suggestion
  author: "azurit, Xhoenix"
```

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951220.yaml
> +            uri: "/anything"
```suggestion
            uri: "/get"
```

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951230.yaml
> +            uri: "/anything"
```suggestion
            uri: "/get"
```

2023-10-19 05:07 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
> +            uri: "/anything"
```suggestion
            uri: "/get"
```

2023-10-19 05:36 UTC, Xhoenix commented
I'll make it a single commit. :)

2023-10-20 05:33 UTC, theseion commented
The change from `/anything` to `/get` causes the tests to fail. The data in the `GET` body will not be reflected by the backend, because `GET`s are not supposed to have a body. Hence, the rule will not detect anything in the response body. Changing the request method to `POST` solves this issue.

2023-10-20 05:34 UTC, theseion requested changes

2023-10-20 05:34 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951220.yaml
> +            uri: "/get"
```suggestion
            uri: "/post"
```

2023-10-20 05:34 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951220.yaml
> +            method: "GET"
```suggestion
            method: "POST"
```

2023-10-20 05:34 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951230.yaml
> +            method: "GET"
```suggestion
            method: "POST"
```

2023-10-20 05:34 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951230.yaml
> +            uri: "/get"
```suggestion
            uri: "/post"
```

2023-10-20 05:34 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
> +            method: "GET"
```suggestion
            method: "POST"
```

2023-10-20 05:34 UTC, theseion commented on tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
> +            uri: "/get"
```suggestion
            uri: "/post"
```

2023-10-21 10:12 UTC, Xhoenix commented
Guys, LGTM.

2023-10-21 12:33 UTC, theseion approved these changes

2023-10-21 12:33 UTC, theseion commented
Thanks!

2023-10-21 12:34 UTC, merged