Backport v3.2 from v3.3
coreruleset/coreruleset pull request #3347
Opened 2023-10-28 06:26 UTC by emphazer

i tried to focus on critical changes.
i skipped https://github.com/coreruleset/coreruleset/pull/1805 for example.

2023-10-31 08:55 UTC, airween requested changes
I reviewed the modifications, see the detailed comments above.

2023-10-31 08:55 UTC, airween commented on CHANGES
> +Fixes and improvements:
As I see you made the fixes which described "CRS bypass" issues, which is fine for me.

2023-10-31 08:55 UTC, airween commented on README.md
> +![GHA build v3.3/dev](https://github.com/coreruleset/coreruleset/workflows/Test%20Ruleset%20against%20matrix/badge.svg?branch=v3.3%2Fdev)
Why do we want to add the next version's URL into the README? Is there any reason?

2023-10-31 08:55 UTC, airween commented on rules/REQUEST-921-PROTOCOL-ATTACK.conf
> +SecRule ARGS_NAMES|ARGS|REQUEST_BODY|XML:/* "@rx (?:get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock)\s+[^\s]+(?:\s+http\/\d|[\r\n])" \
I think this modification is not complete, a part of the new regex is missing after `unlock)`: `(?:\/|\w)`. The line in 3.3 is this:

```
SecRule ARGS_NAMES|ARGS|REQUEST_BODY|XML:/* "@rx (?:get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock)\s+(?:\/|\w)[^\s]*(?:\s+http\/\d|[\r\n])" \
```

2023-10-31 08:55 UTC, airween commented on rules/REQUEST-921-PROTOCOL-ATTACK.conf
> +SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?:\bhttp\/\d|<(?:html|meta)\b)" \
I think there is an extra `\` character here before the `/\d`. In 3.3 the operator's argument is [this](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-921-PROTOCOL-ATTACK.conf#L89):

```
(?:\bhttp/\d|<(?:html|meta)\b)
```
(and not `(?:\bhttp\/\d|<(?:html|meta)\b)`)

2023-10-31 08:55 UTC, airween commented on rules/REQUEST-921-PROTOCOL-ATTACK.conf
> +    tag:'paranoia-level/1',\
We do not have `paranoia-level/N` tags in 3.2, you should remove this tag.

2023-10-31 08:55 UTC, airween commented on rules/REQUEST-921-PROTOCOL-ATTACK.conf
> +    ver:'OWASP_CRS/3.2.0',\
Here you should add tag `OWASP_CRS/3.2.3`, not `3.2.0`.

2023-10-31 08:55 UTC, airween commented on rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
>      setvar:'tx.rfi_parameter_%{MATCHED_VAR_NAME}=%{tx.1}',\
An extra `.` (dot) is missing from here. The correct action is:

```
setvar:'tx.rfi_parameter_%{MATCHED_VAR_NAME}=.%{tx.1}',\
```

2024-02-05 20:18 UTC, theseion commented
We have decided to close this PR and focus on the v4 release.

2024-02-10 15:48 UTC, closed without merging