fix: 932236 932237 932239 FP with word settings
coreruleset/coreruleset pull request #3394
Opened 2023-11-29 18:03 UTC by EsadCetiner

closes #3393

2023-12-01 00:20 UTC, EsadCetiner commented
I know ``set help`` isn't a real command but for whatever reason go-ftw doesn't like ``go --help``, so I've set it as that for 932237 regression test.

2023-12-01 07:51 UTC, dune73 commented
Ping @theseion: Something that ought to be fixed, or do we live with it?

2023-12-03 00:12 UTC, EsadCetiner commented
@theseion sorry, I meant ``set --help`` and not ``go --help``. I wanted to originally use ``set --help`` but the go-ftw tests kept on failing see: https://github.com/coreruleset/coreruleset/actions/runs/7036802306/job/19150223518 and https://github.com/coreruleset/coreruleset/pull/3394/commits/afc9507641eeec5ba6995405b0b61b3675b7fdc3

2023-12-03 16:35 UTC, theseion commented
Thanks. So the issue is the final word boundary match (`\b`) in the regular expression. At a word boundary, two adjacent tokens must not both match `\w` and `\W`, i.e., one must be a word token and the other must not. The space character is a non-word token and the dash character is a non-word token as well, which means the `\b` will not match. I believe that is a bug and should be fixed, possibly by changing `\b` to `\S`.

Issue: https://github.com/coreruleset/coreruleset/issues/3401

Out of curiosity: what is `set --help`? My bash man page doesn't list any long options for `set`...

2023-12-10 20:05 UTC, theseion commented
What kind of shell are you using? `--help` isn't valid in neither bash (3.2) nor zsh.

I also any rule that would block `https://example.com/?test=set --help` (I've checked out your PR branch to test).

2023-12-11 02:40 UTC, EsadCetiner commented
I'm just using whatever comes with Ubuntu, ``5.1.16(1)-release``
and what do you mean by "I also any rule that would block", I'm not sure on what your trying to say?

2023-12-11 05:49 UTC, theseion commented
> and what do you mean by "I also any rule that would block", I'm not sure on what your trying to say?

😅 Sorry about that. I meant to write: I also can't find any rule that would block.

The Ubuntu release will have 3.3.5 or something like that. Rewrote the *nix detection rules heavily, so it doesn't surprise me that there's a difference between that version and 4.0/dev. Detection in `Referer` and `User-Agent` headers is something we introduced in v4, which would explain what you see if you're using 3.3.5.

2023-12-13 12:38 UTC, dune73 commented
What's the status here? Just a final approval and we're good to merge?

2023-12-13 19:41 UTC, theseion requested changes

2023-12-13 19:41 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +              User-Agent: "set help"
Use a command that works more commonly (bash / POSIX), e.g., `set -o history`.

2023-12-13 19:41 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +    desc: "FP with word settings Github Issue #3393"
Don't reference GH issues. At some point in the future, GH will be replaced with something else and the issue numbers will have lost all meaning.

2023-12-13 19:41 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +            uri: /
Uset HTTP verbs in URIs (improves performance with go-ftw and httpbin) (won't repeat for the other locations):
```suggestion
            uri: /get
```

2023-12-13 19:59 UTC, theseion commented
This PR depends on the fix discussed in #3401. I've added a dependency check.

2023-12-13 20:02 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +    desc: "FP with word settings Github Issue #3393"
CRS is moving away from github?
I've removed any references to GH issues

2023-12-13 20:03 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +              User-Agent: "set help"
regression tests are failing again with this, I assume that's because of what's described in #3401?

2023-12-13 20:05 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +    desc: "FP with word settings Github Issue #3393"
No no no 😄. I'm just saying that every software product becomes obsolete at some point. Information should not rely on an external system to exist indefinitely.

2023-12-13 20:05 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +              User-Agent: "set help"
Yes. I've added a dependency to that issue. We need to resolve that first.

2023-12-13 20:09 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +            uri: /
not sure I understand what you mean, do you want me to use a URI path other than root or do you want me to set it to the same as the request method i.e ``/get`` or ``/post``?

2023-12-13 20:26 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +            uri: /
To the same verb as the request method. See https://coreruleset.org/docs/development/contribution_guidelines/#using-the-correct-http-endpoint

2023-12-14 18:46 UTC, theseion approved these changes

2023-12-14 19:57 UTC, theseion commented
https://github.com/coreruleset/coreruleset/pull/3425

2024-01-05 12:03 UTC, EsadCetiner commented
I just noticed that 932237 is running at phase 2, shouldn't it be running at phase 1 for better performance?

2024-01-05 12:38 UTC, M4tteoP commented
I think it has been added to phase 2 because it is a stricter sibling of several rules (932230, 932235, 932250, 932260) that are all running at phase 2 because they match `ARGS`. But I agree that dealing only with headers, it should formally belong to phase 1, just like `932239` (phase:1), sibling rule of 932236 (phase:2)

2024-01-05 19:27 UTC, theseion requested changes

2024-01-05 19:27 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> -            dest_addr: "127.0.0.1"
Instead of removing this test, leave it and simply change `log_contains` to `no_log_contains`.

2024-01-05 19:27 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> +              User-Agent: "https://example.com/?args=settings"
Add this as a new test, convert the old one as I've suggested above.

2024-01-05 19:28 UTC, theseion commented
> I just noticed that 932237 is running at phase 2, shouldn't it be running at phase 1 for better performance?

You're probably right. It's not an urgent issue IMO, but please open an issue.

2024-01-05 20:05 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> -            dest_addr: "127.0.0.1"
is it really needed though, shouldn't the existing test be adaquate to test for FPs?

2024-01-07 14:29 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> -            dest_addr: "127.0.0.1"
There's no other test that tests `set` specifically, and matching of `set` is what you've changed in this PR, so no.

2024-01-07 20:05 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
> -            dest_addr: "127.0.0.1"
hm... ok that makes sense

2024-01-10 19:07 UTC, theseion approved these changes

2024-01-10 19:12 UTC, merged