fix: 9KH-231120-1
coreruleset/coreruleset pull request #3395
Opened 2023-11-29 19:44 UTC by Xhoenix

Added missing Javascript `prompt()` method.

2023-11-29 20:45 UTC, fzipi requested changes
Thanks for your PR.

2023-11-29 20:45 UTC, fzipi commented on tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941390.yaml
> +              Accept: "text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.>
```suggestion
              Accept: "text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.>"
```

2023-11-29 21:50 UTC, dune73 commented
PR looks good to me with the exception of the missing double quote. Happy to merge afterwards.

2023-11-29 22:30 UTC, dune73 approved these changes

2023-12-04 14:14 UTC, fzipi commented
@Xhoenix Can you please add also `confirm`? And maybe adding a new test for it. Also, maybe adding a new reference to https://javascript.info/alert-prompt-confirm.

2023-12-04 19:14 UTC, fzipi commented
@RedXanadu Is there a way to test these two word additions to the rule using your script? I'm afraid adding them will be way more FP prone 🤔

2023-12-12 11:10 UTC, theMiddleBlue approved these changes
LGTM

2023-12-13 19:22 UTC, RedXanadu commented
I'll run before and after numbers and compare…

2023-12-13 22:45 UTC, RedXanadu commented
@Xhoenix A question about the change to `rules/unix-shell.data`: is that a commit that belongs to a different issue/PR? I believe that file relates to the 93216x rules.

2023-12-13 23:52 UTC, RedXanadu commented
The new regular expression does not cause any false positives with the set of 10,000 English test sentences. I even tried the corpus of 1,000,000 sentences just to be safe, and again there were 0 false positives caused by this new regex.

Inevitably, there _will_ be natural language false positives with this eventually. It's easy to create some, e.g.:

* Be prompt (to every meeting!)
* I can confirm (with regret) that the coffee machine is broken.

But it's easy to work backwards from a regex and create false positive payloads… Certainly, nothing triggered in the news article test sentences :slightly_smiling_face:

2023-12-13 23:54 UTC, RedXanadu requested changes
@Xhoenix A question about the change to `rules/unix-shell.data`: is that a commit that fixes / belongs to a different issue/PR? I believe that file relates to the 93216x rules.

2023-12-14 07:50 UTC, dune73 commented
That `pyversions` and `py3versions` had me puzzled too. I suggest we keep PRs separate.

So the idea would be to remove that change from this change and open a separate PR for it. It's a welcome addition to unix-shell.data.

2023-12-14 11:31 UTC, fzipi reviewed
One last small change, so we keep tests clean.

2023-12-14 11:31 UTC, fzipi commented on tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941390.yaml
> +            uri: '/?arg=prompt%28%29'
```suggestion
            uri: '/get?arg=prompt%28%29'
```

2023-12-14 11:31 UTC, fzipi commented on tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941390.yaml
> +            uri: '/?arg=confirm%28%29'
```suggestion
            uri: '/get?arg=confirm%28%29'
```

2023-12-14 12:41 UTC, RedXanadu approved these changes

2023-12-14 12:44 UTC, dune73 commented
Cool. Let's get the HTTP methods into the URI and we're ready to merge.

2023-12-14 13:03 UTC, fzipi approved these changes

2023-12-14 13:05 UTC, merged