feat: Added new method: check for new unlisted tags
coreruleset/coreruleset pull request #3437
Opened 2023-12-23 19:48 UTC by airween

Motivation: store actually used tags in a file and check PR's that any rules contains a new (unlisted) tag or not.

With this step, we can exclude the addition of unwanted new tags or the misspelling of tags and helps to keep tags in a consistent state.

2023-12-24 09:16 UTC, theseion requested changes

2023-12-24 09:16 UTC, theseion commented on util/crs-rules-check/README.md
> +* **Check new tags at rules** - cannot be added to a new tag rule unless it is in the TAGS_USED file
```suggestion
* **Check rule tags** - only tags listed in `TAGS_USED` may be used as tags in rules
```

2023-12-24 09:16 UTC, theseion commented on util/crs-rules-check/README.md
> +    * before you want to add a new tag to a rule, you **must** add it to TAGS_USED file
```suggestion
    * to use a new tag on a rule, it **must** first be registered in the TAGS_USED file
```

2023-12-24 09:16 UTC, theseion commented on util/crs-rules-check/rules-check.py
> +        check tags at rules are exists in TAGS_USED list
```suggestion
        check that only tags from the TAGS_USED file are used
```

2023-12-24 09:16 UTC, theseion commented on util/crs-rules-check/rules-check.py
> +                                'message': "rule has a new tag: '%s' which does not listed in TAGS_USED file, rule id: %d" % (a['act_arg'], ruleid)
```suggestion
                                'message': "rule uses unknown tag: '%s'; only tags registered in the TAGS_USED file may be used; rule id: %d" % (a['act_arg'], ruleid)
```

2023-12-24 09:16 UTC, theseion commented on util/crs-rules-check/rules-check.py
> +    parser.add_argument("-t", "--tags-list", dest="tagslist", help="Path to available tags", required=True)
```suggestion
    parser.add_argument("-t", "--tags-list", dest="tagslist", help="Path to file with permitted tags", required=True)
```

2023-12-24 09:16 UTC, theseion commented on util/crs-rules-check/rules-check.py
> +            # remove empty items, if there is
```suggestion
            # remove empty items, if any
```

2023-12-24 10:02 UTC, theseion submitted a review, later dismissed

2023-12-24 10:30 UTC, airween commented
Please do not merge this until other devs haven't seen. I'm curious about others opinion too.

2023-12-28 14:14 UTC, fzipi submitted a review, later dismissed
I think we should name it `APPROVED_TAGS` instead of `USED_TAGS`.

2023-12-28 18:03 UTC, airween commented
> I think we should name it `APPROVED_TAGS` instead of `USED_TAGS`.

Thanks. I wait with the modifications till other opinions.

2023-12-29 15:57 UTC, theseion commented
I like the idea to use `APPROVED_TAGS`.

2024-01-03 15:55 UTC, dune73 commented
No strong feelings on the `APPROVED_TAGS` vs `USED_TAGS` question.

Maybe this config file should not be on the top level, though. It looks a bit out of place. Maybe in tests or util folder.

I like the supplementary `--tags-list` option.

Other than that I do like the general idea of the PR.

2024-01-03 21:06 UTC, airween commented
> Maybe this config file should not be on the top level, though. It looks a bit out of place. Maybe in tests or util folder.

@fzipi, @theseion, @dune73 - please help me what would be the good place for the file of list of tags.

2024-01-05 08:09 UTC, dune73 commented
There are not that many options. Checking the landscape a bit, I think util would be right place. Right next to the file `id-range`.

2024-01-05 19:19 UTC, theseion commented
> > Maybe this config file should not be on the top level, though. It looks a bit out of place. Maybe in tests or util folder.
> 
> @fzipi, @theseion, @dune73 - please help me what would be the good place for the file of list of tags.

For me there are three options, in order of preference:
- top-level
- `util/crs-rules-check`
- `rules`

I wouldn't put it into `rules` because all the files in rules currently pertain to rule content only, not metadata.
I would rather not put it into `util/crs-rules-check` because it's core data, not particularly associated with the rules check script.

2024-01-06 08:51 UTC, airween commented
Thank you all. After thinking about it, may be the top-level isn't a good choice. I wouldn't put it beside the `rules-check` script, because I'm sure it doesn't belong that - it belongs to CRS itself.

I think the `utils` directory will be a goo place.

Adding the cli switch `--tags-list` is a good idea, but then it must be mandatory.

I'm going to rename the file to `APPROVED_TAGS`.

Note: the idea of this feature came from [here](https://github.com/coreruleset/coreruleset/pull/3347#discussion_r1377237481).

2024-01-07 19:15 UTC, airween commented
Every requested modifications are done.

2024-01-09 15:29 UTC, dune73 commented
Given the `APPROVED_TAG` renaming was implemented like @fzipi asked for, I'm dismissing his review and merging. Thank you all.

2024-01-09 15:29 UTC, merged