fix: avoid false positives with words environment and performance (932230 PL1, 932235 PL1, 932260 PL1, 932236 PL2, 932237 PL3, 932239 PL2)
coreruleset/coreruleset pull request #3477
Opened 2024-01-11 07:10 UTC by EsadCetiner

The rules 932230, 932235, 932260, 932236, 932239, 932237, have a false positive with the words environment and performance, the env and perf are being matched. Both false positives have been resolved by adding ``@`` to both env and perf.

closes #3476

2024-01-11 12:45 UTC, dune73 submitted a review, later dismissed

2024-01-11 12:48 UTC, dune73 commented
Thank you very much. Adjusted the PR title slightly.

2024-01-21 09:43 UTC, theseion requested changes

2024-01-21 09:43 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932236.yaml
> +            no_log_contains: id "932236"
From what I understand, this test should expect a match. Am I wrong?
```suggestion
            log_contains: id "932236"
```

2024-01-21 09:43 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932236.yaml
> +            no_log_contains: id "932236"
From what I understand, this test should expect a match. Am I wrong?
```suggestion
            log_contains: id "932236"
```

2024-01-21 10:03 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932236.yaml
> +            no_log_contains: id "932236"
No, your right that's meant to be ``log_contains:``, thanks for catching that

2024-01-21 11:10 UTC, theseion requested changes
The PR title says that more than the two rules for which you've updated tests have FPs. Please add FP tests to those rules as well.

2024-01-21 11:23 UTC, EsadCetiner commented
I've added the missing tests

2024-01-21 11:25 UTC, theseion requested changes

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +            no_log_contains: id "932236"
```suggestion
            no_log_contains: id "932235"
```

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +            no_log_contains: id "932236"
```suggestion
            no_log_contains: id "932235"
```

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +            log_contains: id "932236"
```suggestion
            log_contains: id "932235"
```

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +            log_contains: id "932236"
```suggestion
            log_contains: id "932235"
```

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +            no_log_contains: id "932236"
```suggestion
            no_log_contains: id "932239"
```

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +            uri: /get?args=environment
This rule targets only `Referer` and `User-Agent` headers.

2024-01-21 11:25 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +            no_log_contains: id "932236"
```suggestion
            no_log_contains: id "932260"
```

2024-01-21 11:31 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +            uri: /get?args=environment
😅

2024-01-21 11:58 UTC, EsadCetiner commented
@theseion should I remove the false negative tests for 932235(To fix the failing FN tests), keep the false positive tests and add the FP/FN tests to 932250 since that rule was blocking env but 932235 wasn't? I've also just realized I've forgotten tests for 932230 so I'll add that

2024-01-21 13:08 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +            uri: "/post?args=perf --version"
This test should actually be working but is missing a prefix like `;`:
```suggestion
            uri: "/post?args=;perf --version"
```

2024-01-21 13:09 UTC, theseion commented
> @theseion should I remove the false negative tests for 932235(To fix the failing FN tests), keep the false positive tests and add the FP/FN tests to 932250 since that rule was blocking env but 932235 wasn't? I've also just realized I've forgotten tests for 932230 so I'll add that

One of them should be ok (see comment), the other is definitely in the wrong place (and probably also needs the prefix).

2024-01-21 20:30 UTC, theseion requested changes

2024-01-21 20:30 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +            uri: /get?args=performance
```suggestion
            uri: /get?args=;performance
```

2024-01-21 20:30 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +              referer: "https://example.com/?args=env --version"
```suggestion
              referer: "https://example.com/?args=env%20--version"
```

2024-01-21 20:30 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +              referer: "https://example.com/?args=perf --version"
```suggestion
              referer: "https://example.com/?args=perf%20--version"
```

2024-01-21 20:30 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +  - test_title: 932260-26
You can remove these three tests. Neither `environment` nor `performance` are part of the word list, and if they were, the URL would need to contain something following the command word, like in `args=environment%20--version`.

`env` is a 3 letter word, so it wouldn't be covered by rule 932260.

The last test is ok but checks the wrong rule. It should check 923360, not 932236.

2024-01-22 09:34 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +  - test_title: 932260-26
I've removed tests for env, but perf is being matched within the word performance so shouldn't we still test that?

2024-01-22 09:38 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +              referer: "https://example.com/?args=env --version"
This change causes the tests to fail

2024-01-22 16:57 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +              referer: "https://example.com/?args=env --version"
Leave it then. I've opened an issue for this, as I believe the URL should be decoded properly (#3504).

2024-01-22 17:00 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +  - test_title: 932260-26
I don't get an FP against the sandbox for `/get?args=performance`. Do you?

2024-01-22 17:07 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +              referer: "https://example.com/?args=env --version"
do you want me to revert the change?

2024-01-22 17:07 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +  - test_title: 932260-26
you mean for 932260 specifically? no, there is for 932236
```
$ curl -H "x-crs-paranoia-level: 2" -H "x-format-output: txt-matched-rules" https://sandbox.coreruleset.org/?test=performance

932236 PL2 Remote Command Execution: Unix Command Injection (command without evasion)
949110 PL1 Inbound Anomaly Score Exceeded (Total Score: 5)
980170 PL1 Anomaly Scores: (Inbound Scores: blocking=5, detection=5, per_pl=0-5-0-0, threshold=5) - (Outbound Scores: blocking=0, detection=0, per_pl=0-0-0-0, threshold=4) - (SQLI=0, XSS=0, RFI=0, LFI=0, RCE=5, PHPI=0, HTTP=0, SESS=0, COMBINED_SCORE=5)
```

I mean, it would be good to have it there just in case a future change results in this FP happening at PL-1. perf is included in unix-shell-4andup

2024-01-22 17:09 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
> +              referer: "https://example.com/?args=env --version"
Yes. A PR for the new issue will make this test fail and we can update it then.

2024-01-22 17:10 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +  - test_title: 932260-26
That's true. Just fix the `log_contains` line then ;)

2024-01-22 17:15 UTC, EsadCetiner commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
> +  - test_title: 932260-26
that should've already been fixed

2024-01-22 19:16 UTC, theseion approved these changes

2024-01-22 19:16 UTC, theseion commented
Thanks!

2024-01-22 19:18 UTC, merged