fix: prevent FP against brackets in User-Agent header
coreruleset/coreruleset pull request #3486
Opened 2024-01-14 17:55 UTC by theseion

The Facebook for Android user agent uses a bracket sequence in the user agent string which triggers FPs for rule 932131. The analysis revealed that this issue had already been fixed in 932130, the sibling rule with the same regular expression, but that the regex-assembly file for 932131 did not exist, which is why the regular expression was not updated.

Fixes #3483

2024-01-15 07:41 UTC, dune73 commented
If 932130.ra and 932131.ra need to stay in sync, can't we source one from the other one?

Other than that this looks good to me. Thanks.

2024-01-15 19:44 UTC, theseion commented
Done.

2024-01-15 20:39 UTC, dune73 requested changes

2024-01-15 20:39 UTC, dune73 commented on regex-assembly/932131.ra
Please add a remark that we're sourcing 932130 on purpose (and maybe why). The way it is this looks like a mistake - at least to an uninitiated eye.

2024-01-16 05:47 UTC, theseion commented on regex-assembly/932131.ra
Good point.

2024-01-16 18:08 UTC, dune73 approved these changes

2024-01-16 18:08 UTC, dune73 commented
Thank you.

2024-01-16 18:08 UTC, merged