fix: JX9-231209-1
coreruleset/coreruleset pull request #3509
Opened 2024-01-23 13:23 UTC by Xhoenix

fixes JX9-231209-1

2024-01-24 13:35 UTC, theseion requested changes

2024-01-24 13:35 UTC, theseion commented on regex-assembly/include/unix-shell-evasion-prefix.ra
> +<<<
You might be missing optional white space here, not sure. Please add a couple of tests as this affects about 6 rules.

2024-01-24 16:14 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +    desc: "JX9-231209-1"
```suggestion
    desc: "Block evasion using here string"
```

2024-01-24 16:15 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> +    desc: "JX9-231209-1 with a space"
```suggestion
    desc: "Block evasion using here string with space"
```

2024-01-24 16:17 UTC, theseion commented on regex-assembly/include/unix-shell-evasion-prefix.ra
> +##! time ifconfig and watch ifconfig
```suggestion
##! <some command> ifconfig
```

2024-01-24 16:18 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Here strings can also begin with single quote, double quote or dollar (for expansion or process substitution). Please add tests for those as well.

2024-01-24 17:12 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
As per bash documentation, I've payloads all bash "expansions" and command substitution. Working on a "quote removal" payload...

2024-01-24 20:36 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Not sure what you mean. I was thinking of these:
```shell
cat<<<'foo'
cat<<<"foo"
cat<<<"${foo}"
cat<<<${foo}
cat<<<"$foo"
cat<<<$foo
cat<<<"$(echo foo)"
cat<<<$(echo foo)
```

2024-01-25 05:47 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
The quotes still need backticks to work, but I guess you meant as a part of the original payload.

2024-01-25 08:13 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Are done yet? Should I do another review pass?

2024-01-26 14:58 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Okay, LGTM!

2024-01-26 15:47 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Please duplicate the new tests for 932230, 932231, 932220, 932236, 932238, 932239. All of them are affected by the addition of here strings.

Please also add at least one test (for each rule) that tests the new additions (e.g., `strace`).

2024-01-26 15:56 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
I don't think they're required @theseion. Kindly make any changes if you think necessary.

2024-01-26 20:19 UTC, closed without merging

2024-01-26 20:29 UTC, theseion commented
I messed up the force push. I've opened a new PR with my additions: #3518.

2024-01-27 16:52 UTC, Xhoenix commented
By "if you think necessary", i didn't mean take my PR. 😅