fix: remove 'time' prefix from Windows RCE detection
coreruleset/coreruleset pull request #3528
Opened 2024-02-03 12:26 UTC by theseion

`time` is a Unix command that can be used for RCE evasion, which is why it is included in the RCE prefix for Unix commands. However, no such command (or default alias) exists on Windows. In addition, having `time` in the prefix causes many FPs in natural language, such as in "time for tea".

fixes #3526

2024-02-03 12:28 UTC, theseion commented
For context, `time` was added to 932238 in #2819, IMO by mistake.

2024-02-03 14:10 UTC, fzipi submitted a review, later dismissed
Good find. I agree that it isn't needed.

2024-02-05 00:13 UTC, RedXanadu commented
Re-run the tests for false positives:

From 17 -> 2 FPs in the 10k payload set
From 139 -> 10 FPs in 100k payload set

2024-02-05 00:35 UTC, RedXanadu requested changes
There may be a typo in the new test.

Apart from that, this is a good fix and thank you for writing it :smile:

2024-02-05 00:35 UTC, RedXanadu commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932380.yaml
> +              payload=payload=While this is a challenging time for us all, we are busy helping customers manage playout infrastructure in ways that were just dreams only a couple of years ago.
I think this may be a typo:

```suggestion
              payload=While this is a challenging time for us all, we are busy helping customers manage playout infrastructure in ways that were just dreams only a couple of years ago.
```

2024-02-05 11:21 UTC, RedXanadu approved these changes
Awesome. Thanks again @theseion :slightly_smiling_face:

Merging!

2024-02-05 11:21 UTC, merged