fix: enable checking ARG_LENGTH in tests
coreruleset/coreruleset pull request #3766
Opened 2024-07-08 09:37 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

2024-07-08 16:38 UTC, theseion requested changes

2024-07-08 16:38 UTC, theseion commented on tests/regression/httpd-overrides.yaml
Remove the same from nginx and coraza overrides.

2024-07-08 17:23 UTC, fzipi commented on tests/regression/httpd-overrides.yaml
Removed from nginx, coraza didn't had it.

2024-07-09 04:39 UTC, theseion approved these changes
❤️

2024-07-09 04:40 UTC, merged