fix(942559): cleanup regex
coreruleset/coreruleset pull request #3767
Opened 2024-07-08 15:43 UTC by fzipi

## what

- cleanup regex to have better performance
- try to avoid patterns like `.*` to prevent catastrophic BT
- update regexes for broader functions
- add documentation for json functions in diverse DBs

2025-07-05 04:33 UTC, Xhoenix commented on regex-assembly/942550.ra
> +  \bjson_extract\b[\(\)]*\([^(]*\)
```suggestion
  \bjson_extract\b[^\(]*\([^\)]*\)
```

2025-07-08 14:53 UTC, EsadCetiner commented on rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> +SecRule REQUEST_FILENAME|REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?:::[\s\x0b]*?(/\*[^\*]*\*/)?[\s\x0b]*?jsonb?)?[\s\x0b]*?(?:(?:@|->?)>|<@|\?[&\|]?
```suggestion
SecRule REQUEST_FILENAME|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?:::[\s\x0b]*?(/\*[^\*]*\*/)?[\s\x0b]*?jsonb?)?[\s\x0b]*?(?:(?:@|->?)>|<@|\?[&\|]?|#>>?|[<>]|<-)|(?:(?:@|->?)>|<@|\?[&\|]?|#>>?|[<>]|<-)?[\"'`][\[\{][^#\]\}]*[\]\}]+[\"'`]|\bjson_extract\b[^\(]*\([^\)]*\)" \
```
Exclusion for Google's UTM cookie have been removed as of v4.15.0

2025-07-13 06:41 UTC, theseion commented on regex-assembly/942550.ra
>  ##!> define json_starting_brackets [\[\{]
```suggestion
##!> define json_starting_brackets [[{]
```

2025-07-13 06:41 UTC, theseion commented on regex-assembly/942550.ra
> +##!> define something_except_json_ending_brackets [^\}\]#]*
```suggestion
##!> define something_except_json_ending_brackets [^}\]#]*
```

2025-07-13 06:42 UTC, theseion commented on regex-assembly/942550.ra
> +##!> define json_ending_brackets [\]\}]+
```suggestion
##!> define json_ending_brackets [\]}]+
```

2025-07-13 06:43 UTC, theseion commented on regex-assembly/942550.ra
> +##!> define sql_comment (/\*[^*]*\*/)?
Careful, this can be used to bypass detection by embedding `*` in the comment, e.g., `/* foo * bar */`. You'll need to use `.*?` here, probably.

2025-07-13 06:45 UTC, theseion commented on regex-assembly/942550.ra
> +  \bjson_extract\b[^\(]*\([^\)]*\)
```suggestion
  \bjson_extract\b[^\(]*\([^)]*\)
```

2025-07-13 15:05 UTC, fzipi commented on regex-assembly/942550.ra
> +##!> define sql_comment (/\*[^*]*\*/)?
```suggestion
##!> define sql_comment (/\*.*?\*/)?
```

2025-07-13 15:58 UTC, Xhoenix commented on regex-assembly/942550.ra
> +  \bjson_extract\b[^\(]*\([^)]*\)
```suggestion
  \bjson_extract\b[^(]*\([^)]*\)
```

https://regex101.com/r/qFKSE6/1

2025-07-13 16:09 UTC, Xhoenix commented on regex-assembly/942550.ra
```suggestion

##!+ i

```
Making the regex case insensitive and removing `lowercase` transformation.

2025-07-15 05:14 UTC, theseion requested changes

2025-07-15 05:14 UTC, theseion commented on regex-assembly/942550.ra
>  ##! MySQL: JSON_EXTRACT('{"id": 14, "name": "Aztalan"}', '$.name') = 'Aztalan'
```suggestion
##! MySQL: JSON_EXTRACT('{"id": 14, "name": "Aztalan"}', '$.name') = 'Aztalan'
##! MySQL: SELECT id FROM users WHERE id=JsoN_EXTraCT/**/(/**/'  {"a":1}  '/**/,/**/' $.a '/**/);
```

2025-07-15 05:14 UTC, theseion commented on regex-assembly/942550.ra
>    ##! example: SELECT id FROM users WHERE id=JsoN_EXTraCT/**/(/**/'  {"a":1}  '/**/,/**/' $.a '/**/);
```suggestion
  ##! MySQL
```

2025-07-15 05:14 UTC, theseion commented on rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> +    t:none,t:urlDecodeUni,t:removeWhitespace,\
You're matching whitespace in the regex. If you need that, remove `removeWhitespace`, otherwise, remove the whitespace matches from the regex.

2025-07-16 04:47 UTC, theseion submitted a review, later dismissed

2025-07-16 12:01 UTC, fzipi commented on rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> +    t:none,t:urlDecodeUni,t:removeWhitespace,\
Removed the whitespace matches from the regex. Now we rely on the transformation.

2025-07-17 05:38 UTC, theseion commented on regex-assembly/942550.ra
> +
Move down.
```suggestion
```

2025-07-17 05:39 UTC, theseion commented on regex-assembly/942550.ra
> +##! This regex relies on the `removeWhitespace` transformation.
```suggestion
##! This regex relies on the `removeWhitespace` transformation.

##!+ i
```

2025-08-28 09:41 UTC, Xhoenix commented on regex-assembly/942550.ra
> +##!> define non_greedy_jsonb (?:::{{sql_comment}}jsonb?)?
Is adding comment between `::` and `jsonb` valid syntax? I see that the sql_comment is made optional with `?`

2025-08-30 07:15 UTC, theseion commented on regex-assembly/942550.ra
> +##!> define non_greedy_jsonb (?:::{{sql_comment}}jsonb?)?
Maybe not, but it's certainly possible, depending on the parser implementation. I think it makes sense to expect a comment to work there.

2025-08-30 12:35 UTC, fzipi commented on regex-assembly/942550.ra
> +##!> define non_greedy_jsonb (?:::{{sql_comment}}jsonb?)?
According to https://www.pgtutorial.com/playground/, this works: `select '{"b":2}'::/** something **/jsonb <@ '{"a":1, "b":2}'::jsonb;`
<img width="1614" height="786" alt="image" src="https://github.com/user-attachments/assets/c3a18e12-ad19-4839-8be3-4b5e98e21e20" />

2025-08-30 16:19 UTC, theseion approved these changes

2025-09-09 07:13 UTC, Xhoenix approved these changes

2025-09-09 07:14 UTC, Xhoenix commented
@EsadCetiner Pending for approval.

2025-09-09 07:40 UTC, merged