feat: add new rule to catch invalid character in multipart headers (v3)
coreruleset/coreruleset pull request #3797
Opened 2024-08-19 22:10 UTC by fzipi

Add a new rule `922130` which check if any MULTIPART header contains a non-ascii character.

Fixes 3MU-240701-1 by @luelueking for v3.

2024-08-20 12:14 UTC, fzipi commented
Needs #3798

2024-08-20 13:17 UTC, airween commented
Seems like regression test is failed.

2024-08-20 16:07 UTC, airween requested changes

2024-08-20 16:07 UTC, airween commented on tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
> +---
Meanwhile  I modified the test file, I suggest you to update this. See the new [one](https://github.com/coreruleset/coreruleset/pull/3796/files#diff-7356b747daef268f00c76bc370387da08ab20fbf8bc5a45462d4ada2f98e03bdR1)

2024-08-27 05:27 UTC, theseion commented
Probably requires backporting seclang_parser.

2024-08-27 11:36 UTC, airween commented
> Probably requires backporting seclang_parser.

We don't need. The rule file was invalid: there was an extra space at the beginning of each lines at the new rule. I removed it ([22e59c1](https://github.com/coreruleset/coreruleset/pull/3797/commits/22e59c17b198dfd3d5c3c024a9c7fcef589bc9ef)), now everything is fine.

2024-08-27 11:40 UTC, airween approved these changes
LGTM

2024-08-27 12:00 UTC, merged