fix: prevent using backslash in file names (v3)
coreruleset/coreruleset pull request #3800
Opened 2024-08-20 21:52 UTC by fzipi

Prevents using backslash in file names.

Fixes 3MU-240701-2 for v3.

Thanks to @luelueking for reporting this.

2024-08-23 15:35 UTC, fzipi commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
> +
```suggestion

```

2024-08-23 15:58 UTC, fzipi reviewed
Fix spacing in test.

2024-08-23 15:58 UTC, fzipi commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
> +              Content-Type: application/octet-stream
```suggestion
              Content-Type: application/octet-stream

```

2024-08-23 15:58 UTC, fzipi commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
> +              Content-Type: application/octet-stream
```suggestion
              Content-Type: application/octet-stream

```

2024-08-23 15:58 UTC, fzipi commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
> +              Content-Type: application/octet-stream
```suggestion
              Content-Type: application/octet-stream

```

2024-08-24 07:10 UTC, theseion requested changes

2024-08-24 07:10 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
> +    desc: "Attempted multipart/form-data bypass (920121). Match \\ in FILES_NAMES."
```suggestion
    desc: 'Attempted multipart/form-data bypass (920121). Match \ in FILES.'
```

2024-08-24 07:10 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
> +    desc: "Attempted multipart/form-data bypass (920120). Match \\ in FILES_NAMES."
```suggestion
    desc: 'Attempted multipart/form-data bypass (920120). Match \ in FILES.'
```

2024-08-24 07:10 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
Add tests for `FILES_NAMES`.

2024-08-24 14:27 UTC, fzipi commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
I discussed this with @airween a bit a couple days ago. Let me copy his thoughts here.

Using these rules as example:
```apacheconf
SecRule FILES "@rx .*" \
    "id:1000,\
    phase:2,\
    capture,\
    msg:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    allow"

SecRule FILES_NAMES "@rx .*" \
    "id:1001,\
    phase:2,\
    capture,\
    msg:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    allow"
```
and this payload:
```
--a
Content-Disposition: form-data; name="file";filename="1.jsp"

<%out.print(123)%>
--a--
```
When tested, these are the logs:
```
[Wed Aug 21 21:14:22.490736 2024] [security2:error] [pid 509880:tid 509882] [client ::1:52968] ModSecurity: Warning. Pattern match ".*" at FILES:file. [file "/home/airween/src/coreruleset/rules/temp.conf"] [line "468"] [id "1000"] [msg "FILES:file: 1.jsp"] [hostname "localhost"] [uri "/post"] [unique_id "ZsY8jnwUPHCjdbq0IiOjiwAAAAA"]
[Wed Aug 21 21:14:22.490873 2024] [security2:error] [pid 509880:tid 509882] [client ::1:52968] ModSecurity: Warning. Pattern match ".*" at FILES_NAMES:file. [file "/home/airween/src/coreruleset/rules/temp.conf"] [line "475"] [id "1001"] [msg "FILES_NAMES:file: file"] [hostname "localhost"] [uri "/post"] [unique_id "ZsY8jnwUPHCjdbq0IiOjiwAAAAA"]
```
So as you can see, `FILES` is a collection, where the contents of `name` are in the key and the contents of `filename` in the value. `FILES_NAMES` is also a collection, but it seems that [only carries the names of the variables that _contain a file_](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#user-content-FILES_NAMES). So for this case, it is unusable as variable.

Does this sound reasonable?

TL; DR: we should remove `FILES_NAMES` from this rule probably, and create a new issue to see which other rules include this variable and evaluate if we have benefits on the inclusion.

2024-08-25 15:34 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
Yes, `FILES_NAMES` contains the names of the form fields. However, I can see an application using the form field name as a canonical file name. Consider a form where you upload a CV. The field name could be `cv.pdf`. This is certainly contrived but it's possible. If an application would use this method, then an attacker could simply change the filename by changing the name of the form field.

I think it would simply be safer to use both targets.

2024-08-25 17:57 UTC, theseion approved these changes

2024-08-25 20:49 UTC, merged