test: enable disabled 920480 tests
coreruleset/coreruleset pull request #3801
Opened 2024-08-25 21:28 UTC by fzipi

2024-08-26 06:00 UTC, theseion requested changes

2024-08-26 06:00 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
> +  - test_id: 18
```suggestion
  - test_id: 18
    desc: |
      Use of special charset to hide body payload.
      No space in header.
      See https://www.slideshare.net/SoroushDalili/waf-bypass-techniques-using-http-standard-and-web-servers-behaviour, slide 32.
```

2024-08-26 06:00 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
> +            Content-Type: "application/x-www-form-urlencoded;charset=ibm037" # https://www.slideshare.net/SoroushDalili/waf-bypass-techniques-using-http-standard-and-web-servers-behaviour slide 32
```suggestion
            Content-Type: "application/x-www-form-urlencoded;charset=ibm037"
```

2024-08-26 11:29 UTC, fzipi commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
> +    desc:  Trailing garbage after 'UTF-8'
```suggestion
    desc: Trailing garbage after 'UTF-8'
```

2024-08-26 17:56 UTC, theseion requested changes

2024-08-26 17:56 UTC, theseion commented on tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
> +            Content-Type: "application/x-www-form-urlencoded; charset=UTF-80" # trailing garbage after 'UTF-8'
```suggestion
            Content-Type: "application/x-www-form-urlencoded; charset=UTF-80"
```

2024-08-27 05:27 UTC, theseion approved these changes

2024-08-27 05:28 UTC, merged