feat: add product name tags
coreruleset/coreruleset pull request #3815
Opened 2024-09-08 17:26 UTC by TimDiam0nd

Added tags for internet explorer and node js related rules.

2024-09-08 18:00 UTC, airween commented
Hi @TimDiam0nd,

thanks for the PR.

First of all, could you take a look at [this lintian](https://github.com/coreruleset/coreruleset/actions/runs/10761963621/job/29841733587?pr=3815#step:9:62) error? Seems like the `platform-platform-internet-explorer` is missing from the list.

(But perhaps this is a typo, I'm not sure you want to add a tag with name `platform-platform` :smiley:)

2024-09-08 18:01 UTC, TimDiam0nd commented
Hey, apologies about that, that should be fixed now (i initially wasnt aware of the approved tags list). Happy to rename the nodejs tag to something else if you would like

2024-09-08 18:07 UTC, airween commented
> Hey, apologies about that, that should be fixed now (i initially wasnt aware of the approved tags list). Happy to rename the nodejs tag to something else if you would like

No worries, thanks for contributing.

`platform-node-js` suits me, but you've added another tag (for eg.) [here](https://github.com/coreruleset/coreruleset/pull/3815/files#diff-49c831b25b258f29245a1fa974e05ccdffd3a16e2294bab352750ce88056e2bfR549). All used tags must listen in file `APPROVED_TAGS`.

But what would be good to explain in the [PR's summary](https://github.com/coreruleset/coreruleset/pull/3815#issue-2512491012) is how did you collect the rules what need to have these tags.

2024-09-08 18:12 UTC, airween commented
> but you've added another tag (for eg.) [here](https://github.com/coreruleset/coreruleset/pull/3815/files#diff-49c831b25b258f29245a1fa974e05ccdffd3a16e2294bab352750ce88056e2bfR549).

Sorry, now I see that tag had already added.

2024-09-08 18:16 UTC, TimDiam0nd commented
> But what would be good to explain in the [PR's summary](https://github.com/coreruleset/coreruleset/pull/3815#issue-2512491012) is how did you collect the rules what need to have these tags.
PR Summary updated as per above

2024-09-08 20:06 UTC, fzipi requested changes
Isn't `nodejs` instead of `node-js`?

2024-09-08 20:06 UTC, fzipi commented on rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
> +# https://opsecx.com/index.php/2017/02/08/exploiting-platform-node-js-deserialization-bug-for-remote-code-execution/
This change looks that was part of an automated change. Is the url working?

2024-09-08 20:06 UTC, fzipi commented on rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
> +# https://snyk.io/blog/5-ways-to-prevent-code-injection-in-javascript-and-platform-node-js/
Same here.

2024-09-09 09:32 UTC, TimDiam0nd commented on rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
> +# https://opsecx.com/index.php/2017/02/08/exploiting-platform-node-js-deserialization-bug-for-remote-code-execution/
Apoligies, fixed that

2024-09-13 13:39 UTC, fzipi commented on rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
> +# https://opsecx.com/index.php/2017/02/08/exploiting-platform-node-js-deserialization-bug-for-remote-code-execution/
Maybe it's me, but I don't see the fix... 🤷

2024-09-13 14:31 UTC, RedXanadu commented on rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
> +# https://opsecx.com/index.php/2017/02/08/exploiting-platform-node-js-deserialization-bug-for-remote-code-execution/
Getting a _404 Not Found_ here, for that link..

2024-09-13 14:33 UTC, TimDiam0nd commented on rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
> +# https://opsecx.com/index.php/2017/02/08/exploiting-platform-node-js-deserialization-bug-for-remote-code-execution/
yep really sorry about that, ive finally reverted it all and made sure i havent change the urls in the last commit

2024-09-16 19:04 UTC, RedXanadu commented
Open questions from today's issues meeting:

- The references to "IE XSS filters": is it just that those XSS-matching regular expressions came from Microsoft? And they put them into IE 8 many, many years ago?
- What do we mean by a 'platform' tag? The target of the attack we are detecting? The source of the knowledge to write the rule? The user agent for a would-be attack/vulnerability?

2024-11-05 12:05 UTC, RedXanadu commented
Re-opening as this is unresolved and we decided to investigate it further.

2024-12-24 17:43 UTC, closed without merging