feat: Block AI scraping bots
coreruleset/coreruleset pull request #3852
Opened 2024-10-08 07:34 UTC by highpingblorg

Pull request for issue #3850.

The pull request is still missing tests for the added rule. I've looked through the documentation for testing and I can't seem to find the appropriate way to test for a rule that adds new data, in this case a list of AI scraper User-agents.

Any help and advice is always welcome.

2024-10-08 11:01 UTC, fzipi commented
Thanks for your contribution @highpingblorg!

Writing tests is easy. Maybe taking a quick look at our https://github.com/coreruleset/coreruleset/blob/main/CONTRIBUTING.md, will give you more insights. Here is the Tl; DR version https://github.com/coreruleset/coreruleset/blob/main/CONTRIBUTING.md#writing-tests.

See for example test id 6 [here](https://github.com/coreruleset/coreruleset/blob/316e196cf8beebe66056c1f92bd37547d9f7e76d/tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913100.yaml#L98-L113). You can copy the 913100.yaml file as 913110.yaml and then modify one or two tests to match your input on user-agents.

2024-10-08 11:06 UTC, fzipi reviewed
Looks good! Some small changes.

2024-10-08 11:06 UTC, fzipi commented on rules/REQUEST-913-SCANNER-DETECTION.conf
> +    "id:913101,\
```suggestion
    "id:913110,\
```

Per https://github.com/coreruleset/coreruleset/blob/main/CONTRIBUTING.md#id-numbering-scheme, let's use `913110` as id.

2024-10-08 11:06 UTC, fzipi commented on rules/REQUEST-913-SCANNER-DETECTION.conf
> +    tag:'attack-reputation-scanner',\
```suggestion
    tag:'attack-ai-scraping-bot',\
```

2024-10-08 11:06 UTC, fzipi commented on rules/ai-scrapers-user-agets.data
> +# https://www.anthropic.com/
```suggestion
# AI crawler/scraper bots
# Sources:
# - https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/
# - https://www.anthropic.com/

```

2024-10-10 06:48 UTC, dune73 commented
Thank you for your contribution @highpingblorg.

I see the problem, yet I am skeptical about the proposed solution (like @RedXanadu in the original issue).

For me, this is another iteration of misbehaving bots, nothing really specific AI about it. And it's not really the fact they are exploring the site, but the rate of requests. So what you really need is rate limiting and CRS is just a weak tool that attempts to block them all when the truly malicious ones will simply change their UA.

That's why we removed all these UA based rules beyond the most striking security scanners.

When trying to update the crawler, scanner, bot and what not rules to v4, I assembled a list of around 2K user-agents of dubious renown. The difficulty is getting an overview and doing some useful taxonomy. Lacking that we opted to remove.

But this does not rule out a plugin attempting just that. All it takes somebody to do that and this PR could be a first step. Personally, I would not try to handle AI bots differently from all the other ones. But I might be wrong on this question.

As for this PR, please don't merge before we discussed this in the team.

2024-10-10 06:48 UTC, dune73 requested changes
See https://github.com/coreruleset/coreruleset/pull/3852#issuecomment-2404184049

2024-10-22 13:45 UTC, closed without merging