fix: move sql operators to include file
coreruleset/coreruleset pull request #3901
Opened 2024-10-28 06:43 UTC by Xhoenix

2024-10-28 11:03 UTC, Xhoenix commented
Does the logical operators need to be moved too?

2024-10-28 13:49 UTC, fzipi requested changes
Very good question. What do you think is better?

2024-10-28 15:34 UTC, Xhoenix commented on regex-assembly/942520.ra
>  [|&<>*\/%=^+-]{1,3}
Also, if you read a little above, a url points to the same SQLITE operators page I mentioned earlier.

2024-10-30 09:14 UTC, Xhoenix commented on regex-assembly/942520.ra
>  [|&<>*\/%=^+-]{1,3}
Looks like those are valid operators for MySQL: https://dev.mysql.com/doc/refman/8.4/en/non-typed-operators.html

2024-10-30 09:38 UTC, Xhoenix commented on regex-assembly/942520.ra
>  [|&<>*\/%=^+-]{1,3}
Looks like we've to add `*`, `^`, %, `|`, `+`, `-` to fix the tests for 942520.

2024-10-30 10:06 UTC, Xhoenix commented on regex-assembly/942520.ra
>  [|&<>*\/%=^+-]{1,3}
Also, the main question is should we include the logical operators too. I think we should, including logical operators for other engines too. But then, what about 942120.ra?

2024-12-31 08:35 UTC, theseion commented
I'm not convinced that moving these operators to an include file makes much sense. It's a very small set of tokens that can be shared between only a few rules. In addition, the `include` syntax isn't flexible enough to write expressions with a range expression (it's possible but not straight forward), like `[|&><]{2,3}`. To me, the downsides will outweigh the downside of redundancy in this particular case.

2025-01-01 09:08 UTC, Xhoenix commented
@theseion I decided later to not move rest of the operators, but fzipi still had to reply my question. @fzipi what is your opinion on what @theseion said.

2025-01-03 16:42 UTC, Xhoenix commented on regex-assembly/942520.ra
>  [|&<>*\/%=^+-]{1,3}
@fzipi I had to remove some tests to fix the regression tests error. Is it okay with you, as some of those operators are for mysql?

2025-01-12 14:23 UTC, fzipi commented
Sure, let's not move then and keep it here.

2025-01-12 14:29 UTC, fzipi commented
Sorry for wasting your time @Xhoenix 😞

2025-01-12 14:29 UTC, closed without merging