fix: 932270 FP
coreruleset/coreruleset pull request #3917
Opened 2024-11-01 04:05 UTC by Xhoenix

Fixes #3844

2024-11-01 08:54 UTC, Xhoenix commented
@theseion using the cmdline processor for word boundary makes crs-toolchain throw error. Can you look into this.

2024-11-02 11:17 UTC, theseion commented
Can you give me an example that I can run?

2024-11-02 12:21 UTC, Xhoenix commented
I updated the 932270.ra file with the following content, and `crs-toolchain regex update` throws error:
```
##! Please refer to the documentation at                                                                
##! https://coreruleset.org/docs/development/regex_assembly/.

##! Bash - Tilde Expansion
##! Detects the following patterns which are common in Unix shell scripts and one-liners

##!> cmdline unix
  ~\+$
  ~\+[\d\s]+
  ~\-$
  ~\-[\d\s]+
  ~\d+~
##!<
```

Is this syntax even right, this is what mentioned in our docs. Something about this doesn't seem right to me. How do we put a word boundary on the number.

2024-11-02 17:39 UTC, theseion commented
Works for me with version 2.3.0:
```shell
crs-toolchain regex generate - <<EOF
##!> cmdline unix
heredoc>   ~\+$
heredoc>   ~\+[\d\s]+
heredoc>   ~\-$
heredoc>   ~\-[\d\s]+
heredoc>   ~\d+~
heredoc> ##!<
heredoc> EOF
(?:\+|\x5c-)(?:$|[\s\x0b0-9]+)|[0-9]+
```

2024-11-02 17:39 UTC, theseion commented
Just so we're talking about the same thing, `$` _is not_ a word boundary. It is the _end of line anchor_.

2024-11-02 18:13 UTC, Xhoenix commented
The issue is with `~\d+~` the `~` is a boundary. This is the line causing FPs.

2024-11-07 09:45 UTC, theseion commented
What do you mean by "`~` is a boundary"? In regular expressions, the token `\b` is called "word boundary". `~` has no special meaning. As I showed above, the input is valid. Can you post a reproducible case that fails?

2024-11-09 04:31 UTC, Xhoenix commented
Don't know, but maybe you forgot this: https://coreruleset.org/docs/development/regex_assembly/index.html#description

The ~ is a special token, to prevent issues like this. If this won't work here, can you read the issue and suggest a solution?

2024-11-09 16:26 UTC, theseion commented
> Don't know, but maybe you forgot this: https://coreruleset.org/docs/development/regex_assembly/index.html#description
> 
> The ~ is a special token, to prevent issues like this. If this won't work here, can you read the issue and suggest a solution?

Right. Now I know what you mean. 

I still don't see the problem. On my machine, that snippet works. It also works in the CI pipeline, otherwise you'd see an error in the linting step.
You wrote that you see an error. What does the error say exactly? Which version are you running (`crs-toolchain --version`)?

2024-11-11 06:57 UTC, Xhoenix commented
This is what exactly what I'm getting locally: https://github.com/coreruleset/coreruleset/actions/runs/11773621103/job/32790821426?pr=3917#step:12:82

2024-11-11 07:43 UTC, theseion commented
> Why are you "Quote Replying" my message, it makes it hard to read your reply. Don't worry, I'm not going to delete my message.

That was a mistake.

You're right, it doesn't work. I didn't see it when I tested it because I ran it in a terminal where the toolchain couldn't find the configuration file, so it didn't load any of the evasion replacement strings.

The reason it doesn't work is that `~` and `@` are supposed to be used only as suffixes. Unfortunately, I didn't enforce that behavior, so the toolchain replaces `~`, just as you intended, but the regular expression wasn't designed to be placed anywhere else than at the end.

You'll have to write your own regular expression for what you intended to achieve with `~`. I'll open an issue with crs-toolchain to enforce the positional use of `~` and `@`.

2024-11-13 07:11 UTC, Xhoenix commented
Cool. I'll be watching the progress of the issue.

2025-01-14 07:06 UTC, Xhoenix commented
Is moving the offending rule to PL2 okay, or we need to move it to a higher level?

2025-02-04 07:45 UTC, Xhoenix commented
ping @coreruleset/core-developers

2025-02-05 05:45 UTC, theseion commented
Still on my list.

2025-02-08 08:18 UTC, theseion requested changes

2025-02-08 08:18 UTC, theseion commented on regex-assembly/932270.ra
>  ~\-[\d\s]+
```suggestion
~-$
~-[\d\s]+
```

2025-02-08 08:18 UTC, theseion commented on regex-assembly/932270.ra
>  ~\-$
I think the `$` anchor is a mistake here and on line 7. History expansions can be used with other commands. For example, I can create a file by using `touch ~+/foo` in the current directory.

I think the tests must be expanded to consider expansions in arbitrary positions, not only at the end of a string.

2025-02-08 08:18 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +#
Add a "sibling" comment, e.g. `# This is a sibling of rule 932271` and add a sibling comment to the base rule: `# This rule has a stricter sibling: 932271`

2025-02-08 08:21 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +    ver:'OWASP_CRS/4.11.0-dev',\
```suggestion
    ver:'OWASP_CRS/4.12.0-dev',\
```

2025-02-13 10:52 UTC, Xhoenix commented on regex-assembly/932270.ra
>  ~\-$
Done.

2025-03-30 07:23 UTC, Xhoenix commented
Ping

2025-04-05 14:17 UTC, theseion requested changes

2025-04-05 14:17 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
> +            expect_ids: [932270]
This is a negative test, I think.

2025-04-05 14:17 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
>              expect_ids: [932270]
This should be a negative test.

2025-04-05 14:17 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# This rule has a stricter sibling: 932271
The description below is not correct for the regular expression.

2025-04-05 14:17 UTC, theseion commented on regex-assembly/932270.ra
>  ~\+[\d\s]+
Spaces aren't allowed between the tokens, AFAICT. So `~+ 1` would not be valid (it would just be interpreted as `~+`). The expression should be `~\+\d+`, I think.

But since we already detect `~[+-]` we don't actually need to match more of the suffix and we can just drop `[\d\s]+` entirely.

2025-04-06 04:16 UTC, Xhoenix commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# ~+    $PWD
Take a look at "Case 2" in this url: https://linuxsimply.com/bash-scripting-tutorial/expansion/tilde-expansion/

2025-04-06 06:42 UTC, theseion commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# ~+    $PWD
Not this line, the entire block. This regular expression does not include `~\d`.

2025-04-06 06:59 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
> +            expect_ids: [932270]
Done.

2025-04-06 06:59 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
>              expect_ids: [932270]
Done.

2025-04-06 06:59 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
>              expect_ids: [932270]
Done.

2025-04-06 07:00 UTC, Xhoenix commented on regex-assembly/932270.ra
>  ~\+[\d\s]+
Done.

2025-04-09 10:16 UTC, Xhoenix commented on rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> +# This rule has a stricter sibling: 932271
Updated.

2025-04-12 10:10 UTC, theseion requested changes
Almost there. Just a couple of tests to add.

2025-04-12 10:10 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
Please add the two negative tests for GET / POST of `~\d+`.

2025-04-12 10:10 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932271.yaml
> +  - test_id: 3
add the same negative test for GET

2025-04-12 10:10 UTC, theseion commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932271.yaml
Please add negative tests for `~[+-](?:$|\d+)`.

2025-04-14 05:59 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932271.yaml
Done.

2025-04-14 05:59 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932271.yaml
> +  - test_id: 3
Done.

2025-04-14 05:59 UTC, Xhoenix commented on tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932270.yaml
Done.

2025-04-17 05:12 UTC, theseion approved these changes
Thanks @Xhoenix, I know this took a long time.

2025-04-17 05:13 UTC, merged