feat: add variable to skip response rules
coreruleset/coreruleset pull request #3944
Opened 2024-11-23 16:43 UTC by fzipi

## what

- add variable to skip checking response rules
- this makes explicit for users the choice of disabling it, instead of relying on ` SecResponseBodyAccess` being `On` by default.

## why

- make configuration more verbose about the problems users might face by enabling responses

## references

- #3943

## todo

- add links to RFDoS documentation
- create followup issue in the documentation repository

2024-11-23 19:26 UTC, dune73 commented
Good thinking. I like the approach and I think this is useful.

But it is a lot of skip rules.

What about skipping to the beginning of 959 in a single skip? (Or the end of 959.)

2024-11-23 21:24 UTC, fzipi commented
Definitely a better approach to just skip to the end instead.

2024-11-24 09:44 UTC, theseion requested changes

2024-11-24 09:44 UTC, theseion commented on crs-setup.conf.example
> +# you might be targeted in a Request Filter Denied of Service attack.
```suggestion
# you might be targeted in a Request Filter Denial of Service (RFDoS) attack.
```

2024-11-24 13:56 UTC, fzipi commented
@M4tteoP For the quantitative tests to work (and post the comment) we should use the `pull_request_target` event, but it will only work from the main branch.

2024-11-26 06:04 UTC, theseion approved these changes

2024-11-26 13:28 UTC, fzipi commented
@dune73 Any other comments? Shall we merge?

2024-11-26 13:42 UTC, dune73 commented
This looks good. So fair with me to merge.

One word of caution, you may still want to consider. The variable is called `crs_skip_response_analysis`, yet you are skipping the analysis AND the blocking decision.

I have been thinking about situations where you would want to skip the former but not the latter. So far I can't see such a situation, but conceptually, there is a chance such a situation exists and you might prefer to skip to the beginning of 959.

2024-11-26 13:55 UTC, fzipi commented
Sure. I don't see how variables might be incremented in the case of CRS, but other rules might come into play so we can add it back.

2024-11-26 14:01 UTC, fzipi commented
Add jump in a4b139c5.

2024-11-26 15:23 UTC, dune73 commented
Very good. Thank you.

2024-11-26 15:23 UTC, merged